/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = ModuleRead;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type Difficulty = number;
export type NoName3 = string;
export type NoName4 = string;
export type NoName5 = string;
export type NoName6 = number;
export type NoName7 = number;
export type ID = number;
export type NoName8 = string;
export type NoName9 = number;
export type NoName10 = string;
export type NoName11 = number;
export type NoName12 = string;
export type NoName13 = string;
export type ID1 = number;
export type NoName14 = string;
export type NoName15 = string;
export type ID2 = number;
export type NoName16 = boolean;
export type NoName17 = string;
export type NoName18 = number;
export type NoName19 = string;
export type NoName20 = number;
/**
 * в часах
 */
export type NoName21 = number;
export type ID3 = number;
export type NoName22 = string;
export type ID4 = number;
export type NoName23 = boolean;
export type NoName24 = string;
export type NoName25 = number;
export type NoName26 = number;
export type NoName27 = string;
export type NoName28 = string;
export type NoName29 = number;
export type ID5 = number;
export type NoName30 = number;
export type NoName31 = string;
export type NoName32 = number;
export type NoName33 = string;
export type NoName34 = string;
export type ID6 = number;
export type NoName35 = string;
export type ID7 = number;
export type NoName36 = string;
export type Photo = string;
export type NoName37 = number;
export type NoName38 = string;
export type NoName39 = string;
export type NoName40 = string;
export type NoName41 = string;
export type NoName42 = string;
export type ID8 = number;
export type NoName43 = string;
export type ID9 = number;
export type NoName44 = boolean;
export type NoName45 = string;
export type NoName46 = number;
export type NoName47 = number;
export type ModulesCount = number;
export type NoName48 = string;
export type NoName49 = number;
export type NoName50 = number;
export type NoName51 = number;
export type NoName52 = string;
export type NoName53 = number;
export type NoName54 = number;
export type NoName55 = string;
export type NoName56 = number;
export type ID10 = number;
export type NoName57 = number;
export type NoName58 = number;
export type NoName59 = number;
export type NoName60 = string;
export type NoName61 = number;
export type NoName62 = string;
export type NoName63 = string;

export interface ModuleRead {
    created_at?: NoName;
    deadline_date?: NoName1;
    description?: NoName2;
    difficulty?: Difficulty;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName34;
    id?: ID6;
    manager?: UserInline;
    manager_id?: NoName37;
    name: NoName38;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName53;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName61;
    start_date?: NoName62;
    updated_at?: NoName63;
}
export interface ModuleFunPointInline {
    created_at?: NoName3;
    description?: NoName4;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName11;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName29;
    id?: ID5;
    module_id: NoName30;
    name: NoName31;
    sorting?: NoName32;
    updated_at?: NoName33;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName5;
    factor?: NoName6;
    fun_point_type_id: NoName7;
    id?: ID;
    name: NoName8;
    sorting?: NoName9;
    updated_at?: NoName10;
}
export interface FunPointTypeInline {
    created_at?: NoName12;
    description?: NoName13;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID1;
    name: NoName14;
    organization?: Organization;
    organization_id?: NoName18;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName28;
}
export interface Organization {
    description?: NoName15;
    id?: ID2;
    is_customer?: NoName16;
    name: NoName17;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName19;
    fun_point_type_id: NoName20;
    hours?: NoName21;
    id?: ID3;
    position?: Position;
    position_id: NoName25;
    sorting?: NoName26;
    updated_at?: NoName27;
}
export interface Position {
    description?: NoName22;
    id?: ID4;
    is_verified?: NoName23;
    name: NoName24;
}
export interface UserInline {
    first_name: NoName35;
    id?: ID7;
    last_name: NoName36;
    photo?: Photo;
}
export interface OrganizationProjectInline {
    created_at?: NoName39;
    date_from?: NoName40;
    date_to?: NoName41;
    description?: NoName42;
    id?: ID8;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName46;
    manager?: UserInline;
    manager_id?: NoName47;
    modules_count?: ModulesCount;
    name: NoName48;
    organization?: Organization;
    organization_id: NoName49;
    recruiters?: UserInline[];
    recruiters_ids?: NoName50[];
    resource_managers?: UserInline[];
    resource_managers_ids?: NoName51[];
    updated_at?: NoName52;
}
export interface IndustrySector {
    description?: NoName43;
    id?: ID9;
    is_verified?: NoName44;
    name: NoName45;
}
export interface ModulePositionLaborEstimateInline {
    count?: NoName54;
    created_at?: NoName55;
    hours?: NoName56;
    id?: ID10;
    module_id: NoName57;
    position?: Position;
    position_id: NoName58;
    sorting?: NoName59;
    updated_at?: NoName60;
}
