/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = UserManageRead;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = '-' | 'F' | 'M';
export type ID = number;
export type NoName4 = string;
export type NoName5 = string;
export type NoName6 = number;
export type OrganizationContractorName = string;
export type NoName7 = 'admin' | 'pfm' | 'pm' | 'rm';
export type OrganizationContractorId = number;
export type OrganizationContractorName1 = string;
export type NoName8 = number;
export type OrganizationProjectName = string;
export type NoName9 = 'admin' | 'pfm' | 'pm' | 'rm';
export type NoName10 = string;

export interface UserManageRead {
    birth_date?: NoName;
    email: NoName1;
    first_name?: NoName2;
    gender?: null | NoName3;
    id?: ID;
    last_name?: NoName4;
    middle_name?: NoName5;
    organization_contractors_roles?: UserOrganizationContractorRole[];
    organization_projects_roles?: UserOrganizationProjectRole[];
    phone?: NoName10;
}
export interface UserOrganizationContractorRole {
    organization_contractor_id: NoName6;
    organization_contractor_name?: OrganizationContractorName;
    role: NoName7;
}
export interface UserOrganizationProjectRole {
    organization_contractor_id?: OrganizationContractorId;
    organization_contractor_name?: OrganizationContractorName1;
    organization_project_id: NoName8;
    organization_project_name?: OrganizationProjectName;
    role: NoName9;
}
