/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = Citizenship;
export type ID = number;
export type NoName = string;
export type NoName1 = number;

export interface Citizenship {
    id?: ID;
    name: NoName;
    sorting?: NoName1;
}
