/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = User;
export type NoName = string;
export type ID = number;
/**
 * Отметьте, если пользователь должен считаться активным. Уберите эту отметку вместо удаления учётной записи.
 */
export type NoName1 = boolean;
export type NoName2 = string;
export type NoName3 = string;
export type Photo = string;

export interface User {
    first_name: NoName;
    id?: ID;
    is_active?: NoName1;
    last_login?: NoName2;
    last_name: NoName3;
    photo?: Photo;
}
