/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvCompetenceRead;
export type ID = number;
export type NoName = string;
export type ParentId = string;
export type CompetenceId = number;
export type CvId = number;
export type ID1 = number;
export type Years = number;

export interface CvCompetenceRead {
    competence?: Competence;
    competence_id: CompetenceId;
    cv_id: CvId;
    id?: ID1;
    years?: Years;
}
export interface Competence {
    id?: ID;
    name: NoName;
    parent_id?: ParentId;
}
