/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = City;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type NoName3 = string;
export type ID1 = number;
export type NoName4 = boolean;
export type NoName5 = string;

export interface City {
    country: Country;
    description?: NoName3;
    id?: ID1;
    is_verified?: NoName4;
    name: NoName5;
}
export interface Country {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
}
