/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvCareer;
export type CvId = number;
export type NoName = null | string;
export type NoName1 = null | string;
export type NoName2 = null | string;
export type ID = number;
export type NoName3 = boolean;
export type OrganizationId = number;
export type PositionId = number | null;

export interface CvCareer {
    competencies_ids?: (number | null)[];
    cv_id: CvId;
    date_from?: NoName;
    date_to?: NoName1;
    description?: NoName2;
    id?: ID;
    is_verified?: NoName3;
    organization_id: OrganizationId;
    position_id?: PositionId;
    projects_ids?: (number | null)[];
}
