/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvCareer;
export type NoName = number;
export type NoName1 = number;
export type NoName2 = string;
export type NoName3 = string;
export type NoName4 = string;
export type ID = number;
export type NoName5 = boolean;
export type NoName6 = number;
export type NoName7 = number;
export type NoName8 = number;

export interface CvCareer {
    competencies_ids?: NoName[];
    cv_id: NoName1;
    date_from?: NoName2;
    date_to?: NoName3;
    description?: NoName4;
    id?: ID;
    is_verified?: NoName5;
    organization_id: NoName6;
    position_id?: NoName7;
    projects_ids?: NoName8[];
}
