/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvPosition;
export type NoName = number;
export type ID = number;
export type NoName1 = number;
export type NoName2 = string;
export type YearStarted = number;
export type Years = number;

export interface CvPosition {
    cv_id: NoName;
    id?: ID;
    position_id?: NoName1;
    title?: NoName2;
    year_started?: YearStarted;
    years?: Years;
}
