/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvTimeSlot;
export type CityId = number;
export type CountryId = number;
export type CvId = number;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type ID = number;
export type NoName3 = boolean;
export type NoName4 = boolean;
export type NoName5 = number;
export type TypeOfEmploymentId = number;

export interface CvTimeSlot {
    city_id?: CityId;
    country_id?: CountryId;
    cv_id: CvId;
    date_from?: NoName;
    date_to?: NoName1;
    description?: NoName2;
    id?: ID;
    is_free?: NoName3;
    is_work_permit_required?: NoName4;
    price?: NoName5;
    type_of_employment_id: TypeOfEmploymentId;
}
