/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = ModulePositionLaborEstimateWorkers;
export type NoName = number;
export type PositionName = string;
export type WorkersCount = number;

export interface ModulePositionLaborEstimateWorkers {
    position_id: NoName;
    position_name: PositionName;
    workers_count?: WorkersCount;
}
