/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvCompetence;
export type CompetenceId = number;
export type CvId = number;
export type ID = number;
export type Years = number | null;

export interface CvCompetence {
    competence_id: CompetenceId;
    cv_id: CvId;
    id?: ID;
    years?: Years;
}
