/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = UserManage;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = '-' | 'F' | 'M';
export type ID = number;
/**
 * Отметьте, если пользователь должен считаться активным. Уберите эту отметку вместо удаления учётной записи.
 */
export type NoName4 = boolean;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = number;
export type OrganizationContractorName = string;
export type NoName8 = 'admin' | 'pfm' | 'pm' | 'rm';
export type Password = string;
export type NoName9 = string;

export interface UserManage {
    birth_date?: NoName;
    email: NoName1;
    first_name?: NoName2;
    gender?: null | NoName3;
    id?: ID;
    is_active?: NoName4;
    last_name?: NoName5;
    middle_name?: NoName6;
    organization_contractors_roles?: UserOrganizationContractorRole[];
    password?: Password;
    phone?: NoName9;
}
export interface UserOrganizationContractorRole {
    organization_contractor_id: NoName7;
    organization_contractor_name?: OrganizationContractorName;
    role: NoName8;
}
