/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvTimeSlotRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type NoName3 = string;
export type ID1 = number;
export type NoName4 = boolean;
export type NoName5 = string;
export type NoName6 = number;
export type NoName7 = number;
export type NoName8 = number;
export type NoName9 = string;
export type NoName10 = string;
export type NoName11 = string;
export type ID2 = number;
export type NoName12 = boolean;
export type NoName13 = boolean;
export type NoName14 = 'manual' | 'request_requirement';
export type OrganizationProjectId = number;
export type OrganizationProjectName = string;
export type NoName15 = number;
export type RequestId = number;
export type RequestRequirementId = number;
export type RequestRequirementName = string;
export type RequestTitle = string;
export type NoName16 = string;
export type ID3 = number;
export type NoName17 = boolean;
export type NoName18 = string;
export type NoName19 = number;

export interface CvTimeSlotRead {
    city?: City;
    city_id?: NoName6;
    country?: Country;
    country_id?: NoName7;
    cv_id: NoName8;
    date_from?: NoName9;
    date_to?: NoName10;
    description?: NoName11;
    id?: ID2;
    is_free?: NoName12;
    is_work_permit_required?: NoName13;
    kind?: NoName14;
    organization_project_id?: OrganizationProjectId;
    organization_project_name?: OrganizationProjectName;
    price?: NoName15;
    request_id?: RequestId;
    request_requirement_id?: RequestRequirementId;
    request_requirement_name?: RequestRequirementName;
    request_title?: RequestTitle;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id: NoName19;
}
export interface City {
    country: Country;
    description?: NoName3;
    id?: ID1;
    is_verified?: NoName4;
    name: NoName5;
}
export interface Country {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
}
export interface TypeOfEmployment {
    description?: NoName16;
    id?: ID3;
    is_verified?: NoName17;
    name: NoName18;
}
