/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvTimeSlotRead;
export type NoName2 = string;
export type ID = number;
export type NoName3 = boolean;
export type NoName4 = string;
export type NoName5 = string;
export type ID1 = number;
export type NoName6 = boolean;
export type NoName7 = string;
export type NoName8 = number;
export type NoName9 = number;
export type NoName10 = number;
export type NoName11 = string;
export type NoName12 = string;
export type NoName13 = string;
export type ID2 = number;
export type NoName14 = boolean;
export type NoName15 = boolean;
export type NoName16 = 'manual' | 'request_requirement';
export type OrganizationProjectId = number;
export type OrganizationProjectName = string;
export type NoName17 = number;
export type RequestId = number;
export type RequestRequirementId = number;
export type RequestRequirementName = string;
export type RequestTitle = string;
export type NoName19 = string;
export type ID3 = number;
export type NoName20 = boolean;
export type NoName21 = string;
export type NoName22 = number;

export interface CvTimeSlotRead {
    city?: City;
    city_id?: NoName8;
    country?: Country;
    country_id?: NoName9;
    cv_id: NoName10;
    date_from?: NoName11;
    date_to?: NoName12;
    description?: NoName13;
    id?: ID2;
    is_free?: NoName14;
    is_work_permit_required?: NoName15;
    kind?: NoName16;
    organization_project_id?: OrganizationProjectId;
    organization_project_name?: OrganizationProjectName;
    price?: NoName17;
    request_id?: RequestId;
    request_requirement_id?: RequestRequirementId;
    request_requirement_name?: RequestRequirementName;
    request_title?: RequestTitle;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id: NoName22;
}
export interface City {
    attributes?: NoName;
    country: Country;
    description?: NoName5;
    id?: ID1;
    is_verified?: NoName6;
    name: NoName7;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName {}
export interface Country {
    attributes?: NoName1;
    description?: NoName2;
    id?: ID;
    is_verified?: NoName3;
    name: NoName4;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName1 {}
export interface TypeOfEmployment {
    attributes?: NoName18;
    description?: NoName19;
    id?: ID3;
    is_verified?: NoName20;
    name: NoName21;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName18 {}
