/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = OrganizationProject;
export type NoName = string;
export type ID = number;
export type NoName1 = string;
export type NoName2 = string;
export type ID1 = number;
export type NoName3 = string;
export type OrganizationId = number;

export interface OrganizationProject {
    description?: NoName;
    id?: ID;
    name: NoName1;
    organization: Organization;
    organization_id: OrganizationId;
}
export interface Organization {
    description?: NoName2;
    id?: ID1;
    name: NoName3;
}
