/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = RequestRequirementCv;
export type NoName = string;
export type CvId = string;
export type NoName1 = string;
export type NoName2 = string;
export type ID = number;
export type Date = string;
export type NoName3 = number;
export type NoName4 = number;
export type RequestRequirementId = string;
export type NoName5 = 'canceled' | 'candidate' | 'pre-candidate' | 'worker';
export type NoName6 = string;

export interface RequestRequirementCv {
    created_at?: NoName;
    cv_id?: CvId;
    date_from?: NoName1;
    date_to?: NoName2;
    id?: ID;
    organization_project_card_items?: RequestRequirementCvOrganizationProjectCardItem[];
    rating?: NoName4;
    request_requirement_id?: RequestRequirementId;
    status?: NoName5;
    updated_at?: NoName6;
}
export interface RequestRequirementCvOrganizationProjectCardItem {
    date?: Date;
    id: NoName3;
}
