/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = OrganizationCustomerRead;
export type NoName = number;
export type NoName1 = string;
export type NoName2 = string;
export type ID = number;
export type NoName3 = string;
export type NoName4 = string;

export interface OrganizationCustomerRead {
    contractor_id: NoName;
    created_at?: NoName1;
    description?: NoName2;
    id?: ID;
    name: NoName3;
    updated_at?: NoName4;
}
