/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvDetailWrite;
export type NoName = string;
export type NoName1 = number;
export type NoName2 = number;
export type NoName3 = number;
export type NoName4 = 'all' | 'weekends' | 'workdays';
export type NoName5 = string;
export type NoName6 = 'F' | 'M';
export type ID = number;
export type NoName7 = boolean;
export type NoName8 = string;
export type NoName9 = number;
export type NoName10 = string;
export type NoName11 = number;
export type Photo = string;
export type NoName12 = number;
export type NoName13 = number;
export type NoName14 = string;
export type NoName15 = string;
export type NoName16 = number;
export type NoName17 = number;

export interface CvDetailWrite {
    birth_date?: NoName;
    citizenship_id?: NoName1;
    city_id?: NoName2;
    country_id?: NoName3;
    days_to_contact?: null | NoName4;
    first_name?: NoName5;
    gender?: null | NoName6;
    id?: ID;
    is_resource_owner?: NoName7;
    last_name?: NoName8;
    linked_ids?: NoName9[];
    middle_name?: NoName10;
    organization_contractor_id: NoName11;
    photo?: Photo;
    physical_limitations_ids?: NoName12[];
    price?: NoName13;
    time_to_contact_from?: NoName14;
    time_to_contact_to?: NoName15;
    types_of_employment_ids?: NoName16[];
    user_id?: NoName17;
}
