/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = OrganizationProjectRead;
export type NoName = string;
export type CurrentUserRole = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = string;
export type NoName4 = string;
export type ID = number;
export type NoName5 = string;
export type ID1 = number;
export type NoName6 = boolean;
export type NoName7 = string;
export type NoName8 = number;
export type NoName9 = string;
export type ID2 = number;
export type NoName10 = string;
export type Photo = string;
export type NoName11 = number;
export type ModulesCount = number;
export type NoName12 = string;
export type ContractorId = string;
export type NoName13 = string;
export type NoName14 = string;
export type ID3 = number;
export type NoName15 = boolean;
export type NoName16 = boolean;
export type NoName17 = string;
export type NoName18 = string;
export type NoName19 = number;
export type NoName20 = string;
export type NoName21 = string;

export interface OrganizationProjectRead {
    created_at?: NoName;
    current_user_role?: CurrentUserRole;
    date_from?: NoName1;
    date_to?: NoName2;
    description?: NoName3;
    goals?: NoName4;
    id?: ID;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName8;
    manager?: UserInline;
    manager_id?: NoName11;
    modules_count?: ModulesCount;
    name: NoName12;
    organization_customer?: Organization;
    organization_customer_id: NoName19;
    plan_description?: NoName20;
    updated_at?: NoName21;
}
export interface IndustrySector {
    description?: NoName5;
    id?: ID1;
    is_verified?: NoName6;
    name: NoName7;
}
export interface UserInline {
    first_name: NoName9;
    id?: ID2;
    last_name: NoName10;
    photo?: Photo;
}
export interface Organization {
    contractor_id?: ContractorId;
    created_at?: NoName13;
    description?: NoName14;
    id?: ID3;
    is_contractor?: NoName15;
    is_customer?: NoName16;
    name: NoName17;
    updated_at?: NoName18;
}
