/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = Competence;
export type ID = number;
export type NoName = string;
export type ParentId = string;

export interface Competence {
    id?: ID;
    name: NoName;
    parent_id?: ParentId;
}
