/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = UserManage;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = string;
export type NoName3 = number;
export type OrganizationContractorName = string;
export type NoName4 = 'admin' | 'pfm' | 'pm' | 'rm';
export type OrganizationContractorId = number;
export type OrganizationContractorName1 = string;
export type NoName5 = number;
export type OrganizationProjectName = string;
export type NoName6 = 'admin' | 'pfm' | 'pm' | 'rm';

export interface UserManage {
    email: NoName;
    first_name: NoName1;
    id?: ID;
    last_name: NoName2;
    organization_contractors_roles?: UserOrganizationContractorRole[];
    organization_projects_roles?: UserOrganizationProjectRole[];
}
export interface UserOrganizationContractorRole {
    organization_contractor_id: NoName3;
    organization_contractor_name?: OrganizationContractorName;
    role: NoName4;
}
export interface UserOrganizationProjectRole {
    organization_contractor_id?: OrganizationContractorId;
    organization_contractor_name?: OrganizationContractorName1;
    organization_project_id: NoName5;
    organization_project_name?: OrganizationProjectName;
    role: NoName6;
}
