/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = OrganizationProject;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = string;
export type ID = number;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = string;
export type NoName7 = number;
export type NoName8 = number;
export type NoName9 = number;
export type NoName10 = string;

export interface OrganizationProject {
    created_at?: NoName;
    date_from?: NoName1;
    date_to?: NoName2;
    description?: NoName3;
    id?: ID;
    industry_sector_id?: NoName4;
    manager_id?: NoName5;
    name: NoName6;
    organization_id: NoName7;
    recruiters_ids?: NoName8[];
    resource_managers_ids?: NoName9[];
    updated_at?: NoName10;
}
