/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = Position;
export type NoName = string;
export type ID = number;
export type NoName1 = string;
export type NoName2 = number;

export interface Position {
    description?: NoName;
    id?: ID;
    name: NoName1;
    sorting?: NoName2;
}
