/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvCertificate;
export type NoName = number;
export type NoName1 = number;
export type NoName2 = string;
export type NoName3 = string;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = number;
export type ID = number;
export type NoName7 = boolean;
export type NoName8 = string;
export type NoName9 = string;

export interface CvCertificate {
    competencies_ids?: NoName[];
    cv_id: NoName1;
    date?: NoName2;
    description?: NoName3;
    education_graduate_id: NoName4;
    education_place_id: NoName5;
    education_speciality_id: NoName6;
    id?: ID;
    is_verified?: NoName7;
    name?: NoName8;
    number?: NoName9;
}
