/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = ModulePositionLaborEstimateWrite;
export type NoName = number;
export type NoName1 = string;
export type NoName2 = number;
export type ID = number;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = string;

export interface ModulePositionLaborEstimateWrite {
    count?: NoName;
    created_at?: NoName1;
    hours?: NoName2;
    id?: ID;
    module_id: NoName3;
    position_id: NoName4;
    sorting?: NoName5;
    updated_at?: NoName6;
}
