/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvSetPhoto;
export type ID = number;
export type Photo = null | string;

export interface CvSetPhoto {
    id?: ID;
    photo?: Photo;
}
