/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = RequestRequirementCompetence;
export type NoName = number;
/**
 * `1` : *Менее года*
 * `3` : *1 – 3 года*
 * `5` : *3 - 5 лет*
 * `100` : *Более 5 лет*
 */
export type NoName1 = 1 | 100 | 3 | 5;
export type ID = number;
export type RequestRequirementId = string;
export type NoName2 = number;

export interface RequestRequirementCompetence {
    competence_id: NoName;
    experience_years?: NoName1;
    id?: ID;
    request_requirement_id?: RequestRequirementId;
    sorting?: NoName2;
}
