/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvCertificateRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type ParentId = string;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type ID1 = number;
export type NoName8 = boolean;
export type NoName9 = string;
export type NoName10 = number;
export type NoName11 = string;
export type ID2 = number;
export type NoName12 = boolean;
export type NoName13 = string;
export type NoName14 = number;
export type NoName15 = string;
export type ID3 = number;
export type NoName16 = boolean;
export type NoName17 = string;
export type NoName18 = number;
export type ID4 = number;
export type NoName19 = boolean;
export type NoName20 = string;
export type NoName21 = string;

export interface CvCertificateRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName3[];
    cv_id: NoName4;
    date?: NoName5;
    description?: NoName6;
    education_graduate?: EducationGraduate;
    education_graduate_id: NoName10;
    education_place?: EducationPlace;
    education_place_id: NoName14;
    education_speciality?: EducationSpecialty;
    education_speciality_id: NoName18;
    id?: ID4;
    is_verified?: NoName19;
    name?: NoName20;
    number?: NoName21;
}
export interface CompetenceInline {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    parent_id?: ParentId;
}
export interface EducationGraduate {
    description?: NoName7;
    id?: ID1;
    is_verified?: NoName8;
    name: NoName9;
}
export interface EducationPlace {
    description?: NoName11;
    id?: ID2;
    is_verified?: NoName12;
    name: NoName13;
}
export interface EducationSpecialty {
    description?: NoName15;
    id?: ID3;
    is_verified?: NoName16;
    name: NoName17;
}
