/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvTimeSlot;
export type CityId = number | null;
export type CountryId = number | null;
export type CvId = number;
export type NoName = null | string;
export type NoName1 = null | string;
export type NoName2 = null | string;
export type ID = number;
export type NoName3 = boolean;
export type NoName4 = null | number;
export type TypeOfEmploymentId = number;

export interface CvTimeSlot {
    city_id?: CityId;
    country_id?: CountryId;
    cv_id: CvId;
    date_from?: NoName;
    date_to?: NoName1;
    description?: NoName2;
    id?: ID;
    is_work_permit_required?: NoName3;
    price?: NoName4;
    type_of_employment_id: TypeOfEmploymentId;
}
