/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvTimeSlot;
export type NoName = number;
export type NoName1 = number;
export type NoName2 = number;
export type NoName3 = string;
export type NoName4 = string;
export type NoName5 = string;
export type ID = number;
export type NoName6 = boolean;
export type NoName7 = boolean;
export type NoName8 = number;
export type NoName9 = number;

export interface CvTimeSlot {
    city_id?: NoName;
    country_id?: NoName1;
    cv_id: NoName2;
    date_from?: NoName3;
    date_to?: NoName4;
    description?: NoName5;
    id?: ID;
    is_free?: NoName6;
    is_work_permit_required?: NoName7;
    price?: NoName8;
    type_of_employment_id: NoName9;
}
