/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvCareerRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type ParentId = string;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type CvCareerId = string;
export type NoName8 = string;
export type FileExt = string;
export type NoName9 = string;
export type FileSize = string;
export type ID1 = number;
export type ID2 = number;
export type NoName10 = boolean;
export type ContractorId = string;
export type NoName11 = string;
export type NoName12 = string;
export type ID3 = number;
export type NoName13 = boolean;
export type NoName14 = boolean;
export type NoName15 = string;
export type NoName16 = string;
export type NoName17 = number;
export type NoName18 = string;
export type ID4 = number;
export type NoName19 = boolean;
export type NoName20 = string;
export type NoName21 = number;
export type NoName22 = string;
export type NoName23 = string;
export type NoName24 = string;
export type NoName25 = string;
export type NoName26 = string;
export type ID5 = number;
export type NoName27 = number;
export type NoName28 = number;
export type NoName29 = string;
export type NoName30 = number;
export type NoName31 = string;
export type NoName32 = string;
export type NoName33 = number;

export interface CvCareerRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName3[];
    cv_id: NoName4;
    date_from?: NoName5;
    date_to?: NoName6;
    description?: NoName7;
    files?: CvCareerFileRead[];
    id?: ID2;
    is_verified?: NoName10;
    organization?: Organization;
    organization_id: NoName17;
    position?: Position;
    position_id?: NoName21;
    projects?: OrganizationProject[];
    projects_ids?: NoName33[];
}
export interface CompetenceInline {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    parent_id?: ParentId;
}
export interface CvCareerFileRead {
    cv_career_id?: CvCareerId;
    file?: NoName8;
    file_ext?: FileExt;
    file_name?: NoName9;
    file_size?: FileSize;
    id?: ID1;
}
export interface Organization {
    contractor_id?: ContractorId;
    created_at?: NoName11;
    description?: NoName12;
    id?: ID3;
    is_contractor?: NoName13;
    is_customer?: NoName14;
    name: NoName15;
    updated_at?: NoName16;
}
export interface Position {
    description?: NoName18;
    id?: ID4;
    is_verified?: NoName19;
    name: NoName20;
}
export interface OrganizationProject {
    created_at?: NoName22;
    date_from?: NoName23;
    date_to?: NoName24;
    description?: NoName25;
    goals?: NoName26;
    id?: ID5;
    industry_sector_id?: NoName27;
    manager_id?: NoName28;
    name: NoName29;
    organization_customer_id: NoName30;
    plan_description?: NoName31;
    updated_at?: NoName32;
}
