/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvCareerRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type ParentId = string;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type CvCareerId = string;
export type NoName8 = string;
export type FileExt = string;
export type NoName9 = string;
export type FileSize = string;
export type ID1 = number;
export type ID2 = number;
export type NoName10 = boolean;
export type NoName12 = string;
export type ID3 = number;
export type NoName13 = boolean;
export type NoName14 = string;
export type NoName15 = number;
export type NoName17 = string;
export type ID4 = number;
export type NoName18 = boolean;
export type NoName19 = string;
export type NoName20 = number;
export type NoName21 = string;
export type NoName22 = string;
export type NoName23 = string;
export type NoName24 = string;
export type NoName25 = string;
export type ID5 = number;
export type NoName26 = number;
export type NoName27 = number;
export type NoName28 = number;
export type NoName29 = string;
export type NoName30 = number;
export type NoName31 = number;
export type NoName32 = string;
export type NoName33 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName34 = string;
export type NoName35 = number;

export interface CvCareerRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName3[];
    cv_id: NoName4;
    date_from?: NoName5;
    date_to?: NoName6;
    description?: NoName7;
    files?: CvCareerFileRead[];
    id?: ID2;
    is_verified?: NoName10;
    organization?: Organization;
    organization_id: NoName15;
    position?: Position;
    position_id?: NoName20;
    projects?: OrganizationProject[];
    projects_ids?: NoName35[];
}
export interface CompetenceInline {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    parent_id?: ParentId;
}
export interface CvCareerFileRead {
    cv_career_id?: CvCareerId;
    file?: NoName8;
    file_ext?: FileExt;
    file_name?: NoName9;
    file_size?: FileSize;
    id?: ID1;
}
export interface Organization {
    attributes?: NoName11;
    description?: NoName12;
    id?: ID3;
    is_verified?: NoName13;
    name: NoName14;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName11 {}
export interface Position {
    attributes?: NoName16;
    description?: NoName17;
    id?: ID4;
    is_verified?: NoName18;
    name: NoName19;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName16 {}
export interface OrganizationProject {
    created_at?: NoName21;
    date_from?: NoName22;
    date_to?: NoName23;
    description?: NoName24;
    goals?: NoName25;
    id?: ID5;
    industry_sector_id?: NoName26;
    manager_pfm_id?: NoName27;
    manager_pm_id?: NoName28;
    name: NoName29;
    organization_contractor_id: NoName30;
    organization_customer_id: NoName31;
    plan_description?: NoName32;
    status?: NoName33;
    updated_at?: NoName34;
}
