/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvCareerRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type ParentId = string;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type CvCareerId = string;
export type NoName8 = string;
export type FileExt = string;
export type NoName9 = string;
export type FileSize = string;
export type ID1 = number;
export type ID2 = number;
export type NoName10 = boolean;
export type NoName11 = string;
export type ID3 = number;
export type NoName12 = boolean;
export type NoName13 = string;
export type NoName14 = number;
export type NoName15 = string;
export type ID4 = number;
export type NoName16 = boolean;
export type NoName17 = string;
export type NoName18 = number;
export type NoName19 = string;
export type NoName20 = string;
export type NoName21 = string;
export type NoName22 = string;
export type ID5 = number;
export type NoName23 = number;
export type NoName24 = number;
export type NoName25 = string;
export type NoName26 = number;
export type NoName27 = number;
export type NoName28 = number;
export type NoName29 = string;
export type NoName30 = number;

export interface CvCareerRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName3[];
    cv_id: NoName4;
    date_from?: NoName5;
    date_to?: NoName6;
    description?: NoName7;
    files?: CvCareerFileRead[];
    id?: ID2;
    is_verified?: NoName10;
    organization?: Organization;
    organization_id: NoName14;
    position?: Position;
    position_id?: NoName18;
    projects?: OrganizationProject[];
    projects_ids?: NoName30[];
}
export interface CompetenceInline {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    parent_id?: ParentId;
}
export interface CvCareerFileRead {
    cv_career_id?: CvCareerId;
    file?: NoName8;
    file_ext?: FileExt;
    file_name?: NoName9;
    file_size?: FileSize;
    id?: ID1;
}
export interface Organization {
    description?: NoName11;
    id?: ID3;
    is_customer?: NoName12;
    name: NoName13;
}
export interface Position {
    description?: NoName15;
    id?: ID4;
    is_verified?: NoName16;
    name: NoName17;
}
export interface OrganizationProject {
    created_at?: NoName19;
    date_from?: NoName20;
    date_to?: NoName21;
    description?: NoName22;
    id?: ID5;
    industry_sector_id?: NoName23;
    manager_id?: NoName24;
    name: NoName25;
    organization_id: NoName26;
    recruiters_ids?: NoName27[];
    resource_managers_ids?: NoName28[];
    updated_at?: NoName29;
}
