/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = FunPointTypeDifficultyLevelWrite;
export type NoName = string;
export type NoName1 = number;
export type NoName2 = number;
export type ID = number;
export type NoName3 = string;
export type NoName4 = number;
export type NoName5 = string;

export interface FunPointTypeDifficultyLevelWrite {
    created_at?: NoName;
    factor?: NoName1;
    fun_point_type_id: NoName2;
    id?: ID;
    name: NoName3;
    sorting?: NoName4;
    updated_at?: NoName5;
}
