/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = FunPointTypeRead;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = number;
export type NoName4 = number;
export type ID = number;
export type NoName5 = string;
export type NoName6 = number;
export type NoName7 = string;
export type ID1 = number;
export type NoName8 = string;
export type NoName9 = string;
export type ID2 = number;
export type NoName10 = boolean;
export type NoName11 = string;
export type NoName12 = number;
export type NoName13 = string;
export type NoName14 = number;
/**
 * в часах
 */
export type NoName15 = number;
export type ID3 = number;
export type NoName16 = string;
export type ID4 = number;
export type NoName17 = boolean;
export type NoName18 = string;
export type NoName19 = number;
export type NoName20 = number;
export type NoName21 = string;
export type NoName22 = string;

export interface FunPointTypeRead {
    created_at?: NoName;
    description?: NoName1;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID1;
    name: NoName8;
    organization?: Organization;
    organization_id?: NoName12;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName22;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName2;
    factor?: NoName3;
    fun_point_type_id: NoName4;
    id?: ID;
    name: NoName5;
    sorting?: NoName6;
    updated_at?: NoName7;
}
export interface Organization {
    description?: NoName9;
    id?: ID2;
    is_customer?: NoName10;
    name: NoName11;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName13;
    fun_point_type_id: NoName14;
    hours?: NoName15;
    id?: ID3;
    position?: Position;
    position_id: NoName19;
    sorting?: NoName20;
    updated_at?: NoName21;
}
export interface Position {
    description?: NoName16;
    id?: ID4;
    is_verified?: NoName17;
    name: NoName18;
}
