/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvPositionCompetence;
export type CompetenceId = number;
export type CvPositionId = string;
export type Years = number;

export interface CvPositionCompetence {
    competence_id: CompetenceId;
    cv_position_id?: CvPositionId;
    years?: Years;
}
