/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = RequestRequirementRead;
export type ID = number;
export type NoName = string;
export type ParentId = string;
export type NoName1 = number;
/**
 * `1` : *Менее года*
 * `3` : *1 – 3 года*
 * `5` : *3 - 5 лет*
 * `100` : *Более 5 лет*
 */
export type NoName2 = 1 | 100 | 3 | 5;
export type ID1 = number;
export type RequestRequirementId = string;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = number;
export type NoName8 = number;
export type NoName9 = number;
export type NoName10 = 'all' | 'weekends' | 'workdays';
export type NoName11 = string;
export type NoName12 = 'F' | 'M';
export type ID2 = number;
export type NoName13 = string;
export type NoName14 = number;
export type NoName15 = string;
export type NoName16 = number;
export type Photo = string;
export type NoName17 = number;
export type NoName18 = string;
export type NoName19 = string;
export type NoName20 = number;
export type CvId = string;
export type NoName21 = string;
export type NoName22 = string;
export type ID3 = number;
export type Date = string;
export type NoName23 = number;
export type NoName24 = number;
export type RequestRequirementId1 = string;
export type NoName25 = 'canceled' | 'candidate' | 'pre-candidate' | 'worker';
export type NoName26 = string;
export type NoName27 = string;
export type NoName28 = string;
export type NoName29 = string;
/**
 * float
 */
export type NoName30 = number;
export type ID4 = number;
export type NoName31 = number;
export type NoName32 = string;
export type NoName34 = string;
export type ID5 = number;
export type NoName35 = boolean;
export type NoName36 = string;
export type NoName37 = number;
export type NoName38 = number;
export type NoName39 = number;
export type Status = string;
export type NoName41 = string;
export type ID6 = number;
export type NoName42 = boolean;
export type NoName43 = string;
export type NoName44 = number;
export type NoName45 = string;
export type NoName48 = string;
export type ID7 = number;
export type NoName49 = boolean;
export type NoName50 = string;
export type NoName51 = string;
export type ID8 = number;
export type NoName52 = boolean;
export type NoName53 = string;
export type NoName54 = number;

export interface RequestRequirementRead {
    competencies?: RequestRequirementCompetenceRead[];
    count?: NoName4;
    cv_list?: RequestRequirementCvRead[];
    cv_list_ids?: string[];
    date_from?: NoName27;
    date_to?: NoName28;
    description?: NoName29;
    experience_years?: NoName30;
    id?: ID4;
    max_price?: NoName31;
    name?: NoName32;
    position?: Position;
    position_id?: NoName37;
    request_id: NoName38;
    sorting?: NoName39;
    status?: Status;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id?: NoName44;
    work_location_address?: NoName45;
    work_location_city?: City;
    work_location_city_id?: NoName54;
}
export interface RequestRequirementCompetenceRead {
    competence?: Competence;
    competence_id: NoName1;
    experience_years?: NoName2;
    id?: ID1;
    request_requirement_id?: RequestRequirementId;
    sorting?: NoName3;
}
export interface Competence {
    id?: ID;
    name: NoName;
    parent_id?: ParentId;
}
export interface RequestRequirementCvRead {
    created_at?: NoName5;
    cv?: CvInlineShort;
    cv_id?: CvId;
    date_from?: NoName21;
    date_to?: NoName22;
    id?: ID3;
    organization_project_card_items?: RequestRequirementCvOrganizationProjectCardItem[];
    rating?: NoName24;
    request_requirement_id?: RequestRequirementId1;
    status?: NoName25;
    updated_at?: NoName26;
}
export interface CvInlineShort {
    birth_date?: NoName6;
    citizenship_id?: NoName7;
    city_id?: NoName8;
    country_id?: NoName9;
    days_to_contact?: null | NoName10;
    first_name?: NoName11;
    gender?: null | NoName12;
    id?: ID2;
    last_name?: NoName13;
    manager_rm_id?: NoName14;
    middle_name?: NoName15;
    organization_contractor_id: NoName16;
    photo?: Photo;
    price?: NoName17;
    time_to_contact_from?: NoName18;
    time_to_contact_to?: NoName19;
    user_id?: NoName20;
}
export interface RequestRequirementCvOrganizationProjectCardItem {
    date?: Date;
    id: NoName23;
}
export interface Position {
    attributes?: NoName33;
    description?: NoName34;
    id?: ID5;
    is_verified?: NoName35;
    name: NoName36;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName33 {}
export interface TypeOfEmployment {
    attributes?: NoName40;
    description?: NoName41;
    id?: ID6;
    is_verified?: NoName42;
    name: NoName43;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName40 {}
export interface City {
    attributes?: NoName46;
    country: Country;
    description?: NoName51;
    id?: ID8;
    is_verified?: NoName52;
    name: NoName53;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName46 {}
export interface Country {
    attributes?: NoName47;
    description?: NoName48;
    id?: ID7;
    is_verified?: NoName49;
    name: NoName50;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName47 {}
