/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = OrganizationProjectCardItemTemplate;
export type NoName = string;
export type ID = number;
export type NoName1 = string;
export type NoName2 = number;
export type NoName3 = number;

export interface OrganizationProjectCardItemTemplate {
    description?: NoName;
    id?: ID;
    name: NoName1;
    parent_id?: NoName2;
    positions_ids?: NoName3[];
}
