/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvDetailReadFull;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = boolean;
export type NoName3 = string;
export type ParentId = string;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = string;
export type NoName7 = string;
export type NoName8 = string;
export type CvCareerId = string;
export type NoName9 = string;
export type FileExt = string;
export type NoName10 = string;
export type FileSize = string;
export type ID1 = number;
export type ID2 = number;
export type NoName11 = boolean;
export type ContractorId = string;
export type NoName12 = string;
export type NoName13 = string;
export type ID3 = number;
export type NoName14 = boolean;
export type NoName15 = boolean;
export type NoName16 = string;
export type NoName17 = string;
export type NoName18 = number;
export type NoName19 = string;
export type ID4 = number;
export type NoName20 = boolean;
export type NoName21 = string;
export type NoName22 = number;
export type NoName23 = string;
export type NoName24 = string;
export type NoName25 = string;
export type NoName26 = string;
export type NoName27 = string;
export type ID5 = number;
export type NoName28 = number;
export type NoName29 = number;
export type NoName30 = string;
export type NoName31 = number;
export type NoName32 = string;
export type NoName33 = string;
export type NoName34 = number;
export type NoName35 = number;
export type NoName36 = number;
export type NoName37 = string;
export type NoName38 = string;
export type NoName39 = string;
export type ID6 = number;
export type NoName40 = boolean;
export type NoName41 = string;
export type NoName42 = number;
export type NoName43 = string;
export type ID7 = number;
export type NoName44 = boolean;
export type NoName45 = string;
export type NoName46 = number;
export type NoName47 = string;
export type ID8 = number;
export type NoName48 = boolean;
export type NoName49 = string;
export type NoName50 = number;
export type ID9 = number;
export type NoName51 = boolean;
export type NoName52 = string;
export type NoName53 = string;
export type NoName54 = string;
export type ID10 = number;
export type NoName55 = boolean;
export type NoName56 = string;
export type NoName57 = number;
export type NoName58 = string;
export type ID11 = number;
export type NoName59 = boolean;
export type NoName60 = string;
export type NoName61 = string;
export type ID12 = number;
export type NoName62 = boolean;
export type NoName63 = string;
export type NoName64 = number;
export type NoName65 = string;
export type NoName66 = string;
export type ID13 = number;
export type NoName67 = boolean;
export type NoName68 = string;
export type NoName69 = number;
export type NoName70 = number;
export type ID14 = number;
export type NoName71 = boolean;
export type NoName72 = string;
export type NoName73 = number;
export type NoName74 = 'all' | 'weekends' | 'workdays';
export type NoName75 = number;
export type NoName76 = number;
export type NoName77 = string;
export type NoName78 = string;
export type NoName79 = string;
export type NoName80 = string;
export type NoName81 = number;
export type NoName82 = number;
export type NoName83 = number;
export type ID15 = number;
export type NoName84 = boolean;
export type CvId = string;
export type NoName85 = string;
export type FileExt1 = string;
export type NoName86 = string;
export type FileSize1 = string;
export type ID16 = number;
export type NoName87 = string;
export type NoName88 = 'F' | 'M';
export type ID17 = number;
export type NoName89 = boolean;
export type NoName90 = string;
export type NoName91 = number;
export type NoName92 = string;
export type NoName93 = number;
export type Photo = string;
export type NoName94 = string;
export type ID18 = number;
export type NoName95 = boolean;
export type NoName96 = string;
export type NoName97 = number;
export type ID19 = number;
export type NoName98 = string;
export type ParentId1 = string;
export type NoName99 = number;
export type CvPositionId = string;
export type Years = number;
export type NoName100 = number;
export type NoName101 = number;
export type CvPositionId1 = string;
export type NoName102 = string;
export type FileExt2 = string;
export type NoName103 = string;
export type FileSize2 = string;
export type ID20 = number;
export type ID21 = number;
export type NoName104 = number;
export type NoName105 = string;
export type YearStarted = number;
export type Years1 = number;
export type NoName106 = number;
export type NoName107 = number;
export type NoName108 = number;
export type NoName109 = string;
export type NoName110 = string;
export type NoName111 = string;
export type ID22 = number;
export type NoName112 = string;
export type ID23 = number;
export type NoName113 = boolean;
export type NoName114 = string;
export type NoName115 = number;
export type NoName116 = boolean;
export type NoName117 = string;
export type NoName118 = number;
export type NoName119 = number;
export type Rating = number;
export type NoName120 = number;
/**
 * `1` : *Менее года*
 * `3` : *1 – 3 года*
 * `5` : *3 - 5 лет*
 * `100` : *Более 5 лет*
 */
export type NoName121 = 1 | 100 | 3 | 5;
export type ID24 = number;
export type RequestRequirementId = string;
export type NoName122 = number;
export type NoName123 = number;
export type NoName124 = string;
export type NoName125 = string;
export type NoName126 = string;
/**
 * float
 */
export type NoName127 = number;
export type ID25 = number;
export type NoName128 = number;
export type NoName129 = string;
export type NoName130 = number;
export type NoName131 = string;
export type NoName132 = string;
export type ID26 = number;
export type NoName133 = number;
export type NoName134 = string;
export type ID27 = number;
export type NoName135 = string;
export type Photo1 = string;
export type NoName136 = number;
export type NoName137 = string;
export type NoName138 = string;
export type NoName139 = string;
export type DifficultyFactor = number;
export type NoName140 = string;
export type NoName141 = string;
export type NoName142 = string;
export type NoName143 = number;
export type NoName144 = number;
export type ID28 = number;
export type NoName145 = string;
export type NoName146 = number;
export type NoName147 = string;
export type NoName148 = number;
export type NoName149 = string;
export type NoName150 = string;
export type ID29 = number;
export type NoName151 = string;
export type NoName152 = number;
export type NoName153 = string;
export type NoName154 = number;
/**
 * в часах
 */
export type NoName155 = number;
export type ID30 = number;
export type NoName156 = number;
export type NoName157 = number;
export type NoName158 = string;
export type NoName159 = string;
export type NoName160 = number;
export type ID31 = number;
export type NoName161 = number;
export type NoName162 = string;
export type NoName163 = number;
export type NoName164 = string;
export type NoName165 = string;
export type ID32 = number;
export type NoName166 = number;
export type NoName167 = string;
export type NoName168 = string;
export type CurrentUserRole = string;
export type NoName169 = string;
export type NoName170 = string;
export type NoName171 = string;
export type NoName172 = string;
export type ID33 = number;
export type NoName173 = number;
export type NoName174 = number;
export type ModulesCount = number;
export type NoName175 = string;
export type NoName176 = number;
export type NoName177 = string;
export type NoName178 = string;
export type NoName179 = number;
export type NoName180 = number;
export type NoName181 = string;
export type NoName182 = number;
export type ID34 = number;
export type NoName183 = number;
export type NoName184 = number;
export type NoName185 = number;
export type NoName186 = string;
export type NoName187 = number;
export type NoName188 = string;
export type NoName189 = string;
/**
 * если пусто, заполнится автоматически из расчета пятидневной рабочей недели<br>ПН-ПТ deadline_date-start_date
 */
export type NoName190 = number;
export type NoName191 = number;
export type NoName192 = number;
export type NoName193 = 10 | 20 | 30;
export type NoName194 = number;
export type NoName195 = number;
export type NoName196 = string;
export type NoName197 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName198 = string;
export type ID35 = number;
export type NoName199 = string;
export type NoName200 = number;
export type NoName201 = number;
export type NoName202 = number;
export type NoName203 = string;
export type ID36 = number;
export type NoName204 = boolean;
export type NoName205 = string;
export type NoName206 = number;
export type NoName207 = string;
export type NoName208 = number;
export type NoName209 = number;
export type NoName210 = number;
export type NoName211 = number;
export type NoName212 = string;
export type NoName213 = string;
export type NoName214 = string;
export type ID37 = number;
export type NoName215 = boolean;
export type NoName216 = boolean;
export type NoName217 = 'manual' | 'request_requirement';
export type OrganizationProjectId = number;
export type OrganizationProjectName = string;
export type NoName218 = number;
export type RequestId = number;
export type RequestRequirementId1 = number;
export type RequestRequirementName = string;
export type RequestTitle = string;
export type NoName219 = number;
export type NoName220 = string;
export type NoName221 = string;
export type NoName222 = number;
export type NoName223 = number;

export interface CvDetailReadFull {
    birth_date?: NoName;
    career?: CvCareerRead[];
    certificates?: CvCertificateRead[];
    citizenship?: Citizenship;
    citizenship_id?: NoName57;
    city?: City;
    city_id?: NoName64;
    contacts?: CvContactRead[];
    country?: Country;
    country_id?: NoName73;
    days_to_contact?: null | NoName74;
    education?: CvEducationRead[];
    files?: CvFileRead[];
    first_name?: NoName87;
    gender?: null | NoName88;
    id?: ID17;
    is_resource_owner?: NoName89;
    last_name?: NoName90;
    linked_ids?: NoName91[];
    middle_name?: NoName92;
    organization_contractor_id: NoName93;
    photo?: Photo;
    physical_limitations?: PhysicalLimitation[];
    physical_limitations_ids?: NoName97[];
    positions?: CvPositionRead[];
    price?: NoName106;
    projects?: CvProjectRead[];
    rating: Rating;
    requests_requirements?: CvRequestRequirementInlineSerializer[];
    time_slots?: CvTimeSlotRead[];
    time_to_contact_from?: NoName220;
    time_to_contact_to?: NoName221;
    types_of_employment?: TypeOfEmployment[];
    types_of_employment_ids?: NoName222[];
    user?: UserInline;
    user_id?: NoName223;
}
export interface CvCareerRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName4[];
    cv_id: NoName5;
    date_from?: NoName6;
    date_to?: NoName7;
    description?: NoName8;
    files?: CvCareerFileRead[];
    id?: ID2;
    is_verified?: NoName11;
    organization?: Organization;
    organization_id: NoName18;
    position?: Position;
    position_id?: NoName22;
    projects?: OrganizationProject[];
    projects_ids?: NoName34[];
}
export interface CompetenceInline {
    description?: NoName1;
    id?: ID;
    is_verified?: NoName2;
    name: NoName3;
    parent_id?: ParentId;
}
export interface CvCareerFileRead {
    cv_career_id?: CvCareerId;
    file?: NoName9;
    file_ext?: FileExt;
    file_name?: NoName10;
    file_size?: FileSize;
    id?: ID1;
}
export interface Organization {
    contractor_id?: ContractorId;
    created_at?: NoName12;
    description?: NoName13;
    id?: ID3;
    is_contractor?: NoName14;
    is_customer?: NoName15;
    name: NoName16;
    updated_at?: NoName17;
}
export interface Position {
    description?: NoName19;
    id?: ID4;
    is_verified?: NoName20;
    name: NoName21;
}
export interface OrganizationProject {
    created_at?: NoName23;
    date_from?: NoName24;
    date_to?: NoName25;
    description?: NoName26;
    goals?: NoName27;
    id?: ID5;
    industry_sector_id?: NoName28;
    manager_id?: NoName29;
    name: NoName30;
    organization_customer_id: NoName31;
    plan_description?: NoName32;
    updated_at?: NoName33;
}
export interface CvCertificateRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName35[];
    cv_id: NoName36;
    date?: NoName37;
    description?: NoName38;
    education_graduate?: EducationGraduate;
    education_graduate_id: NoName42;
    education_place?: EducationPlace;
    education_place_id: NoName46;
    education_speciality?: EducationSpecialty;
    education_speciality_id: NoName50;
    id?: ID9;
    is_verified?: NoName51;
    name?: NoName52;
    number?: NoName53;
}
export interface EducationGraduate {
    description?: NoName39;
    id?: ID6;
    is_verified?: NoName40;
    name: NoName41;
}
export interface EducationPlace {
    description?: NoName43;
    id?: ID7;
    is_verified?: NoName44;
    name: NoName45;
}
export interface EducationSpecialty {
    description?: NoName47;
    id?: ID8;
    is_verified?: NoName48;
    name: NoName49;
}
export interface Citizenship {
    description?: NoName54;
    id?: ID10;
    is_verified?: NoName55;
    name: NoName56;
}
export interface City {
    country: Country;
    description?: NoName61;
    id?: ID12;
    is_verified?: NoName62;
    name: NoName63;
}
export interface Country {
    description?: NoName58;
    id?: ID11;
    is_verified?: NoName59;
    name: NoName60;
}
export interface CvContactRead {
    comment?: NoName65;
    contact_type?: ContactType;
    contact_type_id: NoName69;
    cv_id: NoName70;
    id?: ID14;
    is_primary?: NoName71;
    value: NoName72;
}
export interface ContactType {
    description?: NoName66;
    id?: ID13;
    is_verified?: NoName67;
    name: NoName68;
}
export interface CvEducationRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName75[];
    cv_id: NoName76;
    date_from?: NoName77;
    date_to?: NoName78;
    description?: NoName79;
    diploma_number?: NoName80;
    education_graduate?: EducationGraduate;
    education_graduate_id: NoName81;
    education_place?: EducationPlace;
    education_place_id: NoName82;
    education_speciality?: EducationSpecialty;
    education_speciality_id: NoName83;
    id?: ID15;
    is_verified?: NoName84;
}
export interface CvFileRead {
    cv_id?: CvId;
    file?: NoName85;
    file_ext?: FileExt1;
    file_name?: NoName86;
    file_size?: FileSize1;
    id?: ID16;
}
export interface PhysicalLimitation {
    description?: NoName94;
    id?: ID18;
    is_verified?: NoName95;
    name: NoName96;
}
export interface CvPositionRead {
    competencies?: CvPositionCompetenceRead[];
    competencies_ids?: NoName100[];
    cv_id: NoName101;
    files?: CvPositionFileRead[];
    id?: ID21;
    position?: Position;
    position_id?: NoName104;
    title?: NoName105;
    year_started?: YearStarted;
    years?: Years1;
}
export interface CvPositionCompetenceRead {
    competence?: Competence;
    competence_id: NoName99;
    cv_position_id?: CvPositionId;
    years?: Years;
}
export interface Competence {
    id?: ID19;
    name: NoName98;
    parent_id?: ParentId1;
}
export interface CvPositionFileRead {
    cv_position_id?: CvPositionId1;
    file?: NoName102;
    file_ext?: FileExt2;
    file_name?: NoName103;
    file_size?: FileSize2;
    id?: ID20;
}
export interface CvProjectRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName107[];
    cv_id: NoName108;
    date_from?: NoName109;
    date_to?: NoName110;
    description?: NoName111;
    id?: ID22;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName115;
    is_verified?: NoName116;
    name: NoName117;
    organization?: Organization;
    organization_id: NoName118;
    position?: Position;
    position_id: NoName119;
}
export interface IndustrySector {
    description?: NoName112;
    id?: ID23;
    is_verified?: NoName113;
    name: NoName114;
}
export interface CvRequestRequirementInlineSerializer {
    competencies?: RequestRequirementCompetenceRead[];
    count?: NoName123;
    date_from?: NoName124;
    date_to?: NoName125;
    description?: NoName126;
    experience_years?: NoName127;
    id?: ID25;
    max_price?: NoName128;
    name?: NoName129;
    position?: Position;
    position_id?: NoName130;
    request?: CvRequestInlineSerializer;
    request_id: NoName201;
    sorting?: NoName202;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id?: NoName206;
    work_location_address?: NoName207;
    work_location_city?: City;
    work_location_city_id?: NoName208;
}
export interface RequestRequirementCompetenceRead {
    competence?: Competence;
    competence_id: NoName120;
    experience_years?: NoName121;
    id?: ID24;
    request_requirement_id?: RequestRequirementId;
    sorting?: NoName122;
}
export interface CvRequestInlineSerializer {
    deadline_date?: NoName131;
    description?: NoName132;
    id?: ID26;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName133;
    manager?: UserInline;
    manager_id?: NoName136;
    module?: ModuleInline;
    module_id: NoName192;
    priority?: NoName193;
    recruiter?: UserInline;
    recruiter_id?: NoName194;
    resource_manager?: UserInline;
    resource_manager_id?: NoName195;
    start_date?: NoName196;
    status?: NoName197;
    title?: NoName198;
    type?: RequestType;
    type_id?: NoName200;
}
export interface UserInline {
    first_name: NoName134;
    id?: ID27;
    last_name: NoName135;
    photo?: Photo1;
}
export interface ModuleInline {
    created_at?: NoName137;
    deadline_date?: NoName138;
    description?: NoName139;
    difficulty_factor?: DifficultyFactor;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName165;
    id?: ID32;
    manager?: UserInline;
    manager_id?: NoName166;
    name: NoName167;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName179;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName187;
    start_date?: NoName188;
    updated_at?: NoName189;
    work_days_count?: NoName190;
    work_days_hours_count?: NoName191;
}
export interface ModuleFunPointInline {
    created_at?: NoName140;
    description?: NoName141;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName148;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName160;
    id?: ID31;
    module_id: NoName161;
    name: NoName162;
    sorting?: NoName163;
    updated_at?: NoName164;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName142;
    factor?: NoName143;
    fun_point_type_id: NoName144;
    id?: ID28;
    name: NoName145;
    sorting?: NoName146;
    updated_at?: NoName147;
}
export interface FunPointTypeInline {
    created_at?: NoName149;
    description?: NoName150;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID29;
    name: NoName151;
    organization_customer?: Organization;
    organization_customer_id?: NoName152;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName159;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName153;
    fun_point_type_id: NoName154;
    hours?: NoName155;
    id?: ID30;
    position?: Position;
    position_id: NoName156;
    sorting?: NoName157;
    updated_at?: NoName158;
}
export interface OrganizationProjectInline {
    created_at?: NoName168;
    current_user_role?: CurrentUserRole;
    date_from?: NoName169;
    date_to?: NoName170;
    description?: NoName171;
    goals?: NoName172;
    id?: ID33;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName173;
    manager?: UserInline;
    manager_id?: NoName174;
    modules_count?: ModulesCount;
    name: NoName175;
    organization_customer?: Organization;
    organization_customer_id: NoName176;
    plan_description?: NoName177;
    updated_at?: NoName178;
}
export interface ModulePositionLaborEstimateInline {
    count?: NoName180;
    created_at?: NoName181;
    hours?: NoName182;
    id?: ID34;
    module_id: NoName183;
    position?: Position;
    position_id: NoName184;
    sorting?: NoName185;
    updated_at?: NoName186;
}
export interface RequestType {
    id?: ID35;
    name: NoName199;
}
export interface TypeOfEmployment {
    description?: NoName203;
    id?: ID36;
    is_verified?: NoName204;
    name: NoName205;
}
export interface CvTimeSlotRead {
    city?: City;
    city_id?: NoName209;
    country?: Country;
    country_id?: NoName210;
    cv_id: NoName211;
    date_from?: NoName212;
    date_to?: NoName213;
    description?: NoName214;
    id?: ID37;
    is_free?: NoName215;
    is_work_permit_required?: NoName216;
    kind?: NoName217;
    organization_project_id?: OrganizationProjectId;
    organization_project_name?: OrganizationProjectName;
    price?: NoName218;
    request_id?: RequestId;
    request_requirement_id?: RequestRequirementId1;
    request_requirement_name?: RequestRequirementName;
    request_title?: RequestTitle;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id: NoName219;
}
