/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvDetailReadFull;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = boolean;
export type NoName3 = string;
export type ParentId = string;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = string;
export type NoName7 = string;
export type NoName8 = string;
export type CvCareerId = string;
export type NoName9 = string;
export type FileExt = string;
export type NoName10 = string;
export type FileSize = string;
export type ID1 = number;
export type ID2 = number;
export type NoName11 = boolean;
export type NoName12 = string;
export type NoName13 = string;
export type ID3 = number;
export type NoName14 = boolean;
export type NoName15 = boolean;
export type NoName16 = string;
export type NoName17 = string;
export type NoName18 = number;
export type NoName19 = string;
export type ID4 = number;
export type NoName20 = boolean;
export type NoName21 = string;
export type NoName22 = number;
export type NoName23 = string;
export type NoName24 = string;
export type NoName25 = string;
export type NoName26 = string;
export type NoName27 = string;
export type ID5 = number;
export type NoName28 = number;
export type NoName29 = number;
export type NoName30 = string;
export type NoName31 = number;
export type NoName32 = number;
export type NoName33 = string;
export type NoName34 = string;
export type NoName35 = number;
export type NoName36 = number;
export type NoName37 = number;
export type NoName38 = string;
export type NoName39 = string;
export type NoName40 = string;
export type ID6 = number;
export type NoName41 = boolean;
export type NoName42 = string;
export type NoName43 = number;
export type NoName44 = string;
export type ID7 = number;
export type NoName45 = boolean;
export type NoName46 = string;
export type NoName47 = number;
export type NoName48 = string;
export type ID8 = number;
export type NoName49 = boolean;
export type NoName50 = string;
export type NoName51 = number;
export type ID9 = number;
export type NoName52 = boolean;
export type NoName53 = string;
export type NoName54 = string;
export type NoName55 = string;
export type ID10 = number;
export type NoName56 = boolean;
export type NoName57 = string;
export type NoName58 = number;
export type NoName59 = string;
export type ID11 = number;
export type NoName60 = boolean;
export type NoName61 = string;
export type NoName62 = string;
export type ID12 = number;
export type NoName63 = boolean;
export type NoName64 = string;
export type NoName65 = number;
export type NoName66 = string;
export type NoName67 = string;
export type ID13 = number;
export type NoName68 = boolean;
export type NoName69 = string;
export type NoName70 = number;
export type NoName71 = number;
export type ID14 = number;
export type NoName72 = boolean;
export type NoName73 = string;
export type NoName74 = number;
export type NoName75 = 'all' | 'weekends' | 'workdays';
export type NoName76 = number;
export type NoName77 = number;
export type NoName78 = string;
export type NoName79 = string;
export type NoName80 = string;
export type NoName81 = string;
export type NoName82 = number;
export type NoName83 = number;
export type NoName84 = number;
export type ID15 = number;
export type NoName85 = boolean;
export type CvId = string;
export type NoName86 = string;
export type FileExt1 = string;
export type NoName87 = string;
export type FileSize1 = string;
export type ID16 = number;
export type NoName88 = string;
export type NoName89 = 'F' | 'M';
export type ID17 = number;
export type NoName90 = boolean;
export type NoName91 = string;
export type NoName92 = number;
export type NoName93 = string;
export type NoName94 = number;
export type Photo = string;
export type NoName95 = string;
export type ID18 = number;
export type NoName96 = boolean;
export type NoName97 = string;
export type NoName98 = number;
export type ID19 = number;
export type NoName99 = string;
export type ParentId1 = string;
export type NoName100 = number;
export type CvPositionId = string;
export type Years = number;
export type NoName101 = number;
export type NoName102 = number;
export type CvPositionId1 = string;
export type NoName103 = string;
export type FileExt2 = string;
export type NoName104 = string;
export type FileSize2 = string;
export type ID20 = number;
export type ID21 = number;
export type NoName105 = number;
export type NoName106 = string;
export type YearStarted = number;
export type Years1 = number;
export type NoName107 = number;
export type NoName108 = number;
export type NoName109 = number;
export type NoName110 = string;
export type NoName111 = string;
export type NoName112 = string;
export type ID22 = number;
export type NoName113 = string;
export type ID23 = number;
export type NoName114 = boolean;
export type NoName115 = string;
export type NoName116 = number;
export type NoName117 = boolean;
export type NoName118 = string;
export type NoName119 = number;
export type NoName120 = number;
export type Rating = number;
export type NoName121 = number;
/**
 * `1` : *Менее года*
 * `3` : *1 – 3 года*
 * `5` : *3 - 5 лет*
 * `100` : *Более 5 лет*
 */
export type NoName122 = 1 | 100 | 3 | 5;
export type ID24 = number;
export type RequestRequirementId = string;
export type NoName123 = number;
export type NoName124 = number;
export type NoName125 = string;
export type NoName126 = string;
export type NoName127 = string;
/**
 * float
 */
export type NoName128 = number;
export type ID25 = number;
export type NoName129 = number;
export type NoName130 = string;
export type NoName131 = number;
export type NoName132 = string;
export type NoName133 = string;
export type ID26 = number;
export type NoName134 = number;
export type NoName135 = string;
export type NoName136 = string;
export type NoName137 = '-' | 'F' | 'M';
export type ID27 = number;
export type NoName138 = string;
export type NoName139 = string;
export type NoName140 = string;
export type Photo1 = string;
export type NoName141 = number;
export type NoName142 = string;
export type NoName143 = string;
export type NoName144 = string;
export type DifficultyFactor = number;
export type NoName145 = string;
export type NoName146 = string;
export type NoName147 = string;
export type NoName148 = number;
export type NoName149 = number;
export type ID28 = number;
export type NoName150 = string;
export type NoName151 = number;
export type NoName152 = string;
export type NoName153 = number;
export type NoName154 = string;
export type NoName155 = string;
export type ID29 = number;
export type NoName156 = string;
export type NoName157 = number;
export type NoName158 = string;
export type NoName159 = number;
/**
 * в часах
 */
export type NoName160 = number;
export type ID30 = number;
export type NoName161 = number;
export type NoName162 = number;
export type NoName163 = string;
export type NoName164 = string;
export type NoName165 = number;
export type ID31 = number;
export type NoName166 = number;
export type NoName167 = string;
export type NoName168 = number;
export type NoName169 = string;
export type NoName170 = string;
export type ID32 = number;
export type NoName171 = number;
export type NoName172 = string;
export type NoName173 = string;
export type NoName174 = string;
export type NoName175 = string;
export type NoName176 = string;
export type NoName177 = string;
export type ID33 = number;
export type NoName178 = number;
export type NoName179 = number;
export type NoName180 = string;
export type NoName181 = number;
export type NoName182 = number;
export type NoName183 = string;
export type NoName184 = string;
export type NoName185 = number;
export type NoName186 = number;
export type NoName187 = string;
export type NoName188 = number;
export type ID34 = number;
export type NoName189 = number;
export type NoName190 = number;
export type NoName191 = number;
export type NoName192 = string;
export type NoName193 = number;
export type NoName194 = string;
export type NoName195 = string;
/**
 * если пусто, заполнится автоматически из расчета пятидневной рабочей недели<br>ПН-ПТ deadline_date-start_date
 */
export type NoName196 = number;
export type NoName197 = number;
export type NoName198 = number;
export type NoName199 = 10 | 20 | 30;
export type NoName200 = number;
export type NoName201 = number;
export type NoName202 = string;
export type NoName203 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName204 = string;
export type ID35 = number;
export type NoName205 = string;
export type NoName206 = number;
export type NoName207 = number;
export type NoName208 = number;
export type NoName209 = string;
export type ID36 = number;
export type NoName210 = boolean;
export type NoName211 = string;
export type NoName212 = number;
export type NoName213 = string;
export type NoName214 = number;
export type NoName215 = number;
export type NoName216 = number;
export type NoName217 = number;
export type NoName218 = string;
export type NoName219 = string;
export type NoName220 = string;
export type ID37 = number;
export type NoName221 = boolean;
export type NoName222 = boolean;
export type NoName223 = 'manual' | 'request_requirement';
export type OrganizationProjectId = number;
export type OrganizationProjectName = string;
export type NoName224 = number;
export type RequestId = number;
export type RequestRequirementId1 = number;
export type RequestRequirementName = string;
export type RequestTitle = string;
export type NoName225 = number;
export type NoName226 = string;
export type NoName227 = string;
export type NoName228 = number;
export type NoName229 = number;

export interface CvDetailReadFull {
    birth_date?: NoName;
    career?: CvCareerRead[];
    certificates?: CvCertificateRead[];
    citizenship?: Citizenship;
    citizenship_id?: NoName58;
    city?: City;
    city_id?: NoName65;
    contacts?: CvContactRead[];
    country?: Country;
    country_id?: NoName74;
    days_to_contact?: null | NoName75;
    education?: CvEducationRead[];
    files?: CvFileRead[];
    first_name?: NoName88;
    gender?: null | NoName89;
    id?: ID17;
    is_resource_owner?: NoName90;
    last_name?: NoName91;
    linked_ids?: NoName92[];
    middle_name?: NoName93;
    organization_contractor_id: NoName94;
    photo?: Photo;
    physical_limitations?: PhysicalLimitation[];
    physical_limitations_ids?: NoName98[];
    positions?: CvPositionRead[];
    price?: NoName107;
    projects?: CvProjectRead[];
    rating: Rating;
    requests_requirements?: CvRequestRequirementInlineSerializer[];
    time_slots?: CvTimeSlotRead[];
    time_to_contact_from?: NoName226;
    time_to_contact_to?: NoName227;
    types_of_employment?: TypeOfEmployment[];
    types_of_employment_ids?: NoName228[];
    user?: UserInline;
    user_id?: NoName229;
}
export interface CvCareerRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName4[];
    cv_id: NoName5;
    date_from?: NoName6;
    date_to?: NoName7;
    description?: NoName8;
    files?: CvCareerFileRead[];
    id?: ID2;
    is_verified?: NoName11;
    organization?: Organization;
    organization_id: NoName18;
    position?: Position;
    position_id?: NoName22;
    projects?: OrganizationProject[];
    projects_ids?: NoName35[];
}
export interface CompetenceInline {
    description?: NoName1;
    id?: ID;
    is_verified?: NoName2;
    name: NoName3;
    parent_id?: ParentId;
}
export interface CvCareerFileRead {
    cv_career_id?: CvCareerId;
    file?: NoName9;
    file_ext?: FileExt;
    file_name?: NoName10;
    file_size?: FileSize;
    id?: ID1;
}
export interface Organization {
    created_at?: NoName12;
    description?: NoName13;
    id?: ID3;
    is_contractor?: NoName14;
    is_customer?: NoName15;
    name: NoName16;
    updated_at?: NoName17;
}
export interface Position {
    description?: NoName19;
    id?: ID4;
    is_verified?: NoName20;
    name: NoName21;
}
export interface OrganizationProject {
    created_at?: NoName23;
    date_from?: NoName24;
    date_to?: NoName25;
    description?: NoName26;
    goals?: NoName27;
    id?: ID5;
    industry_sector_id?: NoName28;
    manager_id?: NoName29;
    name: NoName30;
    organization_contractor_id: NoName31;
    organization_customer_id: NoName32;
    plan_description?: NoName33;
    updated_at?: NoName34;
}
export interface CvCertificateRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName36[];
    cv_id: NoName37;
    date?: NoName38;
    description?: NoName39;
    education_graduate?: EducationGraduate;
    education_graduate_id: NoName43;
    education_place?: EducationPlace;
    education_place_id: NoName47;
    education_speciality?: EducationSpecialty;
    education_speciality_id: NoName51;
    id?: ID9;
    is_verified?: NoName52;
    name?: NoName53;
    number?: NoName54;
}
export interface EducationGraduate {
    description?: NoName40;
    id?: ID6;
    is_verified?: NoName41;
    name: NoName42;
}
export interface EducationPlace {
    description?: NoName44;
    id?: ID7;
    is_verified?: NoName45;
    name: NoName46;
}
export interface EducationSpecialty {
    description?: NoName48;
    id?: ID8;
    is_verified?: NoName49;
    name: NoName50;
}
export interface Citizenship {
    description?: NoName55;
    id?: ID10;
    is_verified?: NoName56;
    name: NoName57;
}
export interface City {
    country: Country;
    description?: NoName62;
    id?: ID12;
    is_verified?: NoName63;
    name: NoName64;
}
export interface Country {
    description?: NoName59;
    id?: ID11;
    is_verified?: NoName60;
    name: NoName61;
}
export interface CvContactRead {
    comment?: NoName66;
    contact_type?: ContactType;
    contact_type_id: NoName70;
    cv_id: NoName71;
    id?: ID14;
    is_primary?: NoName72;
    value: NoName73;
}
export interface ContactType {
    description?: NoName67;
    id?: ID13;
    is_verified?: NoName68;
    name: NoName69;
}
export interface CvEducationRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName76[];
    cv_id: NoName77;
    date_from?: NoName78;
    date_to?: NoName79;
    description?: NoName80;
    diploma_number?: NoName81;
    education_graduate?: EducationGraduate;
    education_graduate_id: NoName82;
    education_place?: EducationPlace;
    education_place_id: NoName83;
    education_speciality?: EducationSpecialty;
    education_speciality_id: NoName84;
    id?: ID15;
    is_verified?: NoName85;
}
export interface CvFileRead {
    cv_id?: CvId;
    file?: NoName86;
    file_ext?: FileExt1;
    file_name?: NoName87;
    file_size?: FileSize1;
    id?: ID16;
}
export interface PhysicalLimitation {
    description?: NoName95;
    id?: ID18;
    is_verified?: NoName96;
    name: NoName97;
}
export interface CvPositionRead {
    competencies?: CvPositionCompetenceRead[];
    competencies_ids?: NoName101[];
    cv_id: NoName102;
    files?: CvPositionFileRead[];
    id?: ID21;
    position?: Position;
    position_id?: NoName105;
    title?: NoName106;
    year_started?: YearStarted;
    years?: Years1;
}
export interface CvPositionCompetenceRead {
    competence?: Competence;
    competence_id: NoName100;
    cv_position_id?: CvPositionId;
    years?: Years;
}
export interface Competence {
    id?: ID19;
    name: NoName99;
    parent_id?: ParentId1;
}
export interface CvPositionFileRead {
    cv_position_id?: CvPositionId1;
    file?: NoName103;
    file_ext?: FileExt2;
    file_name?: NoName104;
    file_size?: FileSize2;
    id?: ID20;
}
export interface CvProjectRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName108[];
    cv_id: NoName109;
    date_from?: NoName110;
    date_to?: NoName111;
    description?: NoName112;
    id?: ID22;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName116;
    is_verified?: NoName117;
    name: NoName118;
    organization?: Organization;
    organization_id: NoName119;
    position?: Position;
    position_id: NoName120;
}
export interface IndustrySector {
    description?: NoName113;
    id?: ID23;
    is_verified?: NoName114;
    name: NoName115;
}
export interface CvRequestRequirementInlineSerializer {
    competencies?: RequestRequirementCompetenceRead[];
    count?: NoName124;
    date_from?: NoName125;
    date_to?: NoName126;
    description?: NoName127;
    experience_years?: NoName128;
    id?: ID25;
    max_price?: NoName129;
    name?: NoName130;
    position?: Position;
    position_id?: NoName131;
    request?: CvRequestInlineSerializer;
    request_id: NoName207;
    sorting?: NoName208;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id?: NoName212;
    work_location_address?: NoName213;
    work_location_city?: City;
    work_location_city_id?: NoName214;
}
export interface RequestRequirementCompetenceRead {
    competence?: Competence;
    competence_id: NoName121;
    experience_years?: NoName122;
    id?: ID24;
    request_requirement_id?: RequestRequirementId;
    sorting?: NoName123;
}
export interface CvRequestInlineSerializer {
    deadline_date?: NoName132;
    description?: NoName133;
    id?: ID26;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName134;
    manager?: UserInline;
    manager_id?: NoName141;
    module?: ModuleInline;
    module_id: NoName198;
    priority?: NoName199;
    recruiter?: UserInline;
    recruiter_id?: NoName200;
    resource_manager?: UserInline;
    resource_manager_id?: NoName201;
    start_date?: NoName202;
    status?: NoName203;
    title?: NoName204;
    type?: RequestType;
    type_id?: NoName206;
}
export interface UserInline {
    birth_date?: NoName135;
    first_name?: NoName136;
    gender?: null | NoName137;
    id?: ID27;
    last_name?: NoName138;
    middle_name?: NoName139;
    phone?: NoName140;
    photo?: Photo1;
}
export interface ModuleInline {
    created_at?: NoName142;
    deadline_date?: NoName143;
    description?: NoName144;
    difficulty_factor?: DifficultyFactor;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName170;
    id?: ID32;
    manager?: UserInline;
    manager_id?: NoName171;
    name: NoName172;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName185;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName193;
    start_date?: NoName194;
    updated_at?: NoName195;
    work_days_count?: NoName196;
    work_days_hours_count?: NoName197;
}
export interface ModuleFunPointInline {
    created_at?: NoName145;
    description?: NoName146;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName153;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName165;
    id?: ID31;
    module_id: NoName166;
    name: NoName167;
    sorting?: NoName168;
    updated_at?: NoName169;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName147;
    factor?: NoName148;
    fun_point_type_id: NoName149;
    id?: ID28;
    name: NoName150;
    sorting?: NoName151;
    updated_at?: NoName152;
}
export interface FunPointTypeInline {
    created_at?: NoName154;
    description?: NoName155;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID29;
    name: NoName156;
    organization_customer?: Organization;
    organization_customer_id?: NoName157;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName164;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName158;
    fun_point_type_id: NoName159;
    hours?: NoName160;
    id?: ID30;
    position?: Position;
    position_id: NoName161;
    sorting?: NoName162;
    updated_at?: NoName163;
}
export interface OrganizationProjectInline {
    created_at?: NoName173;
    date_from?: NoName174;
    date_to?: NoName175;
    description?: NoName176;
    goals?: NoName177;
    id?: ID33;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName178;
    manager?: UserInline;
    manager_id?: NoName179;
    name: NoName180;
    organization_contractor?: Organization;
    organization_contractor_id: NoName181;
    organization_customer?: Organization;
    organization_customer_id: NoName182;
    plan_description?: NoName183;
    updated_at?: NoName184;
}
export interface ModulePositionLaborEstimateInline {
    count?: NoName186;
    created_at?: NoName187;
    hours?: NoName188;
    id?: ID34;
    module_id: NoName189;
    position?: Position;
    position_id: NoName190;
    sorting?: NoName191;
    updated_at?: NoName192;
}
export interface RequestType {
    id?: ID35;
    name: NoName205;
}
export interface TypeOfEmployment {
    description?: NoName209;
    id?: ID36;
    is_verified?: NoName210;
    name: NoName211;
}
export interface CvTimeSlotRead {
    city?: City;
    city_id?: NoName215;
    country?: Country;
    country_id?: NoName216;
    cv_id: NoName217;
    date_from?: NoName218;
    date_to?: NoName219;
    description?: NoName220;
    id?: ID37;
    is_free?: NoName221;
    is_work_permit_required?: NoName222;
    kind?: NoName223;
    organization_project_id?: OrganizationProjectId;
    organization_project_name?: OrganizationProjectName;
    price?: NoName224;
    request_id?: RequestId;
    request_requirement_id?: RequestRequirementId1;
    request_requirement_name?: RequestRequirementName;
    request_title?: RequestTitle;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id: NoName225;
}
