/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = EducationPlace;
export type EducationPlace = null | {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    [k: string]: unknown;
};
export type NoName = null | string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
