/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = City;
export type ID = number;
export type NoName = string;
export type NoName1 = number;
export type ID1 = number;
export type NoName2 = string;
export type NoName3 = number;

export interface City {
    country: Country;
    id?: ID1;
    name: NoName2;
    sorting?: NoName3;
}
export interface Country {
    id?: ID;
    name: NoName;
    sorting?: NoName1;
}
