/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = City;
export type NoName2 = string;
export type ID = number;
export type NoName3 = boolean;
export type NoName4 = string;
export type NoName5 = string;
export type ID1 = number;
export type NoName6 = boolean;
export type NoName7 = string;

export interface City {
    attributes?: NoName;
    country: Country;
    description?: NoName5;
    id?: ID1;
    is_verified?: NoName6;
    name: NoName7;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName {}
export interface Country {
    attributes?: NoName1;
    description?: NoName2;
    id?: ID;
    is_verified?: NoName3;
    name: NoName4;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName1 {}
