/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvProject;
export type NoName = number;
export type NoName1 = number;
export type NoName2 = string;
export type NoName3 = string;
export type NoName4 = string;
export type ID = number;
export type NoName5 = number;
export type NoName6 = boolean;
export type NoName7 = string;
export type NoName8 = number;
export type NoName9 = number;

export interface CvProject {
    competencies_ids?: NoName[];
    cv_id: NoName1;
    date_from?: NoName2;
    date_to?: NoName3;
    description?: NoName4;
    id?: ID;
    industry_sector_id?: NoName5;
    is_verified?: NoName6;
    name: NoName7;
    organization_id: NoName8;
    position_id: NoName9;
}
