/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvProject;
export type CvId = number;
export type NoName = null | string;
export type NoName1 = null | string;
export type NoName2 = null | string;
export type ID = number;
export type IndustrySectorId = number | null;
export type NoName3 = boolean;
export type NoName4 = string;
export type OrganizationId = number;
export type PositionId = number;

export interface CvProject {
    competencies_ids?: (number | null)[];
    cv_id: CvId;
    date_from?: NoName;
    date_to?: NoName1;
    description?: NoName2;
    id?: ID;
    industry_sector_id?: IndustrySectorId;
    is_verified?: NoName3;
    name: NoName4;
    organization_id: OrganizationId;
    position_id: PositionId;
}
