/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = FunPointTypePositionLaborEstimateWrite;
export type NoName = string;
export type NoName1 = number;
/**
 * в часах
 */
export type NoName2 = number;
export type ID = number;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;

export interface FunPointTypePositionLaborEstimateWrite {
    created_at?: NoName;
    fun_point_type_id: NoName1;
    hours?: NoName2;
    id?: ID;
    position_id: NoName3;
    sorting?: NoName4;
    updated_at?: NoName5;
}
