/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = OrganizationContractor;
export type NoName = string;
export type CurrentUserRole = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = boolean;
export type NoName3 = string;
export type NoName4 = string;

export interface OrganizationContractor {
    created_at?: NoName;
    current_user_role?: CurrentUserRole;
    description?: NoName1;
    id?: ID;
    is_customer?: NoName2;
    name: NoName3;
    updated_at?: NoName4;
}
