/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = TimeSheetRowRead;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = number;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = 'all' | 'weekends' | 'workdays';
export type NoName6 = string;
export type NoName7 = 'F' | 'M';
export type ID = number;
export type NoName8 = string;
export type NoName9 = number;
export type NoName10 = string;
export type NoName11 = number;
export type Photo = string;
export type NoName12 = number;
export type NoName13 = string;
export type NoName14 = string;
export type NoName15 = number;
export type NoName16 = number;
export type NoName17 = string;
export type NoName18 = string;
export type ID1 = number;
export type NoName19 = string;
export type NoName20 = string;
export type ID2 = number;
export type NoName21 = number;
export type NoName22 = string;
export type NoName23 = string;
export type NoName24 = '-' | 'F' | 'M';
export type ID3 = number;
export type NoName25 = string;
export type NoName26 = string;
export type NoName27 = string;
export type Photo1 = string;
export type NoName28 = number;
export type NoName29 = string;
export type NoName30 = string;
export type NoName31 = string;
export type DifficultyFactor = number;
export type NoName32 = string;
export type NoName33 = string;
export type NoName34 = string;
export type NoName35 = number;
export type NoName36 = number;
export type ID4 = number;
export type NoName37 = string;
export type NoName38 = number;
export type NoName39 = string;
export type NoName40 = number;
export type NoName41 = string;
export type NoName42 = string;
export type ID5 = number;
export type NoName43 = string;
export type NoName44 = string;
export type EMail = string;
export type NoName45 = string;
export type NoName46 = string;
export type NoName47 = string;
export type NoName48 = string;
export type ID6 = number;
export type NoName49 = boolean;
export type NoName50 = boolean;
export type NoName51 = boolean;
export type NoName52 = string;
export type NoName53 = string;
export type NoName54 = string;
export type NoName55 = string;
export type NoName56 = number;
export type NoName57 = string;
export type NoName58 = number;
/**
 * в часах
 */
export type NoName59 = number;
export type ID7 = number;
export type NoName60 = string;
export type ID8 = number;
export type NoName61 = boolean;
export type NoName62 = string;
export type NoName63 = number;
export type NoName64 = number;
export type NoName65 = string;
export type NoName66 = string;
export type NoName67 = number;
export type ID9 = number;
export type NoName68 = number;
export type NoName69 = string;
export type NoName70 = number;
export type NoName71 = string;
export type NoName72 = string;
export type ID10 = number;
export type NoName73 = string;
export type NoName74 = string;
export type NoName75 = string;
export type NoName76 = string;
export type NoName77 = string;
export type NoName78 = string;
export type ID11 = number;
export type NoName79 = string;
export type ID12 = number;
export type NoName80 = boolean;
export type NoName81 = string;
export type NoName82 = number;
export type NoName83 = number;
export type NoName84 = number;
export type NoName85 = string;
export type NoName86 = number;
export type NoName87 = number;
export type NoName88 = string;
export type RequestsRequirementsCountTotal = number;
export type NoName89 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName90 = string;
export type NoName91 = number;
export type NoName92 = number;
export type NoName93 = string;
export type NoName94 = number;
export type ID13 = number;
export type NoName95 = number;
export type NoName96 = number;
export type NoName97 = number;
export type NoName98 = string;
export type NoName99 = number;
export type NoName100 = string;
export type NoName101 = string;
/**
 * если пусто, заполнится автоматически из расчета пятидневной рабочей недели<br>ПН-ПТ deadline_date-start_date
 */
export type NoName102 = number;
export type NoName103 = number;
export type NoName104 = number;
export type NoName105 = 10 | 20 | 30;
export type NoName106 = string;
export type NoName107 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName108 = string;
export type NoName109 = number;
export type NoName110 = number;
export type NoName111 = string;
export type NoName112 = string;
export type NoName113 = string;
export type NoName114 = number;

export interface TimeSheetRowRead {
    created_at?: NoName;
    cv: CvInlineShort;
    cv_id: NoName16;
    date_from?: NoName17;
    date_to?: NoName18;
    id?: ID1;
    request: RequestInline;
    request_id: NoName110;
    task_description?: NoName111;
    task_name: NoName112;
    updated_at?: NoName113;
    work_time: NoName114;
}
export interface CvInlineShort {
    birth_date?: NoName1;
    citizenship_id?: NoName2;
    city_id?: NoName3;
    country_id?: NoName4;
    days_to_contact?: null | NoName5;
    first_name?: NoName6;
    gender?: null | NoName7;
    id?: ID;
    last_name?: NoName8;
    manager_rm_id?: NoName9;
    middle_name?: NoName10;
    organization_contractor_id: NoName11;
    photo?: Photo;
    price?: NoName12;
    time_to_contact_from?: NoName13;
    time_to_contact_to?: NoName14;
    user_id?: NoName15;
}
export interface RequestInline {
    deadline_date?: NoName19;
    description?: NoName20;
    id?: ID2;
    industry_sector_id?: NoName21;
    manager_rm?: UserInline;
    manager_rm_id?: NoName28;
    module?: ModuleInline;
    module_id: NoName104;
    priority?: NoName105;
    start_date?: NoName106;
    status?: NoName107;
    title?: NoName108;
    type_id?: NoName109;
}
export interface UserInline {
    birth_date?: NoName22;
    first_name?: NoName23;
    gender?: null | NoName24;
    id?: ID3;
    last_name?: NoName25;
    middle_name?: NoName26;
    phone?: NoName27;
    photo?: Photo1;
}
export interface ModuleInline {
    created_at?: NoName29;
    deadline_date?: NoName30;
    description?: NoName31;
    difficulty_factor?: DifficultyFactor;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName72;
    id?: ID10;
    name: NoName73;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName91;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName99;
    start_date?: NoName100;
    updated_at?: NoName101;
    work_days_count?: NoName102;
    work_days_hours_count?: NoName103;
}
export interface ModuleFunPointInline {
    created_at?: NoName32;
    description?: NoName33;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName40;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName67;
    id?: ID9;
    module_id: NoName68;
    name: NoName69;
    sorting?: NoName70;
    updated_at?: NoName71;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName34;
    factor?: NoName35;
    fun_point_type_id: NoName36;
    id?: ID4;
    name: NoName37;
    sorting?: NoName38;
    updated_at?: NoName39;
}
export interface FunPointTypeInline {
    created_at?: NoName41;
    description?: NoName42;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID5;
    name: NoName43;
    organization_customer?: MainOrganization;
    organization_customer_id?: NoName56;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName66;
}
export interface MainOrganization {
    contact_person?: NoName44;
    contacts_email?: EMail;
    contacts_phone?: NoName45;
    created_at?: NoName46;
    current_user_roles?: ('admin' | 'pfm' | 'pm' | 'rm')[];
    description?: NoName47;
    general_manager_name?: NoName48;
    id?: ID6;
    is_contractor?: NoName49;
    is_customer?: NoName50;
    is_partner?: NoName51;
    legal_name?: NoName52;
    name: NoName53;
    short_name?: NoName54;
    updated_at?: NoName55;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName57;
    fun_point_type_id: NoName58;
    hours?: NoName59;
    id?: ID7;
    position?: Position;
    position_id: NoName63;
    sorting?: NoName64;
    updated_at?: NoName65;
}
export interface Position {
    description?: NoName60;
    id?: ID8;
    is_verified?: NoName61;
    name: NoName62;
}
export interface OrganizationProjectInline {
    created_at?: NoName74;
    current_user_roles?: ('admin' | 'pfm' | 'pm' | 'rm')[];
    date_from?: NoName75;
    date_to?: NoName76;
    description?: NoName77;
    goals?: NoName78;
    id?: ID11;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName82;
    manager_pfm?: UserInline;
    manager_pfm_id?: NoName83;
    manager_pm?: UserInline;
    manager_pm_id?: NoName84;
    name: NoName85;
    organization_contractor?: MainOrganization;
    organization_contractor_id: NoName86;
    organization_customer?: MainOrganization;
    organization_customer_id: NoName87;
    plan_description?: NoName88;
    requests_requirements_count_by_status?: RequestsRequirementsCountByStatus;
    requests_requirements_count_total?: RequestsRequirementsCountTotal;
    status?: NoName89;
    updated_at?: NoName90;
}
export interface IndustrySector {
    description?: NoName79;
    id?: ID12;
    is_verified?: NoName80;
    name: NoName81;
}
export interface RequestsRequirementsCountByStatus {}
export interface ModulePositionLaborEstimateInline {
    count?: NoName92;
    created_at?: NoName93;
    hours?: NoName94;
    id?: ID13;
    module_id: NoName95;
    position?: Position;
    position_id: NoName96;
    sorting?: NoName97;
    updated_at?: NoName98;
}
