/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvTimeSlotRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type NoName3 = string;
export type ID1 = number;
export type NoName4 = boolean;
export type NoName5 = string;
export type CityId = number;
export type CountryId = number;
export type CvId = number;
export type NoName6 = string;
export type NoName7 = string;
export type NoName8 = string;
export type ID2 = number;
export type NoName9 = boolean;
export type NoName10 = boolean;
export type NoName11 = 'manual' | 'request_requirement';
export type OrganizationProjectId = number;
export type OrganizationProjectName = string;
export type NoName12 = number;
export type RequestId = number;
export type RequestRequirementId = number;
export type RequestRequirementName = string;
export type RequestTitle = string;
export type NoName13 = string;
export type ID3 = number;
export type NoName14 = boolean;
export type NoName15 = string;
export type TypeOfEmploymentId = number;

export interface CvTimeSlotRead {
    city?: City;
    city_id?: CityId;
    country?: Country;
    country_id?: CountryId;
    cv_id: CvId;
    date_from?: NoName6;
    date_to?: NoName7;
    description?: NoName8;
    id?: ID2;
    is_free?: NoName9;
    is_work_permit_required?: NoName10;
    kind?: NoName11;
    organization_project_id?: OrganizationProjectId;
    organization_project_name?: OrganizationProjectName;
    price?: NoName12;
    request_id?: RequestId;
    request_requirement_id?: RequestRequirementId;
    request_requirement_name?: RequestRequirementName;
    request_title?: RequestTitle;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id: TypeOfEmploymentId;
}
export interface City {
    country: Country;
    description?: NoName3;
    id?: ID1;
    is_verified?: NoName4;
    name: NoName5;
}
export interface Country {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
}
export interface TypeOfEmployment {
    description?: NoName13;
    id?: ID3;
    is_verified?: NoName14;
    name: NoName15;
}
