/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvTimeSlotRead;
export type City = null | {
    country: Country;
    description?: NoName3;
    id?: ID1;
    is_verified?: NoName4;
    name: NoName5;
    [k: string]: unknown;
};
export type Country = null | {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    [k: string]: unknown;
};
export type NoName = null | string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type NoName3 = null | string;
export type ID1 = number;
export type NoName4 = boolean;
export type NoName5 = string;
export type CityId = number | null;
export type CountryId = number | null;
export type CvId = number;
export type NoName6 = null | string;
export type NoName7 = null | string;
export type NoName8 = null | string;
export type ID2 = number;
export type NoName9 = boolean;
export type NoName10 = null | number;
export type TypeOfEmployment = null | {
    description?: NoName11;
    id?: ID3;
    is_verified?: NoName12;
    name: NoName13;
    [k: string]: unknown;
};
export type NoName11 = null | string;
export type ID3 = number;
export type NoName12 = boolean;
export type NoName13 = string;
export type TypeOfEmploymentId = number;

export interface CvTimeSlotRead {
    city?: City;
    city_id?: CityId;
    country?: Country;
    country_id?: CountryId;
    cv_id: CvId;
    date_from?: NoName6;
    date_to?: NoName7;
    description?: NoName8;
    id?: ID2;
    is_work_permit_required?: NoName9;
    price?: NoName10;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id: TypeOfEmploymentId;
}
