/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = Request;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = number;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = 10 | 20 | 30;
export type NoName6 = number;
export type NoName7 = number;
export type NoName8 = string;
export type NoName9 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName10 = string;
export type NoName11 = number;

export interface Request {
    deadline_date?: NoName;
    description?: NoName1;
    id?: ID;
    industry_sector_id?: NoName2;
    manager_id?: NoName3;
    module_id: NoName4;
    priority?: NoName5;
    recruiter_id?: NoName6;
    resource_manager_id?: NoName7;
    start_date?: NoName8;
    status?: NoName9;
    title?: NoName10;
    type_id?: NoName11;
}
