/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvProjectRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type ParentId = string;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type ID1 = number;
export type NoName9 = string;
export type ID2 = number;
export type NoName10 = boolean;
export type NoName11 = string;
export type NoName12 = number;
export type NoName13 = boolean;
export type NoName14 = string;
export type NoName16 = string;
export type ID3 = number;
export type NoName17 = boolean;
export type NoName18 = string;
export type NoName19 = number;
export type NoName21 = string;
export type ID4 = number;
export type NoName22 = boolean;
export type NoName23 = string;
export type NoName24 = number;

export interface CvProjectRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName3[];
    cv_id: NoName4;
    date_from?: NoName5;
    date_to?: NoName6;
    description?: NoName7;
    id?: ID1;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName12;
    is_verified?: NoName13;
    name: NoName14;
    organization?: Organization;
    organization_id: NoName19;
    position?: Position;
    position_id: NoName24;
}
export interface CompetenceInline {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    parent_id?: ParentId;
}
export interface IndustrySector {
    attributes?: NoName8;
    description?: NoName9;
    id?: ID2;
    is_verified?: NoName10;
    name: NoName11;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName8 {}
export interface Organization {
    attributes?: NoName15;
    description?: NoName16;
    id?: ID3;
    is_verified?: NoName17;
    name: NoName18;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName15 {}
export interface Position {
    attributes?: NoName20;
    description?: NoName21;
    id?: ID4;
    is_verified?: NoName22;
    name: NoName23;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName20 {}
