/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvProjectRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type ParentId = string;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type ID1 = number;
export type NoName8 = string;
export type ID2 = number;
export type NoName9 = boolean;
export type NoName10 = string;
export type NoName11 = number;
export type NoName12 = boolean;
export type NoName13 = string;
export type NoName14 = string;
export type ID3 = number;
export type NoName15 = boolean;
export type NoName16 = string;
export type NoName17 = number;
export type NoName18 = string;
export type ID4 = number;
export type NoName19 = boolean;
export type NoName20 = string;
export type NoName21 = number;

export interface CvProjectRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName3[];
    cv_id: NoName4;
    date_from?: NoName5;
    date_to?: NoName6;
    description?: NoName7;
    id?: ID1;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName11;
    is_verified?: NoName12;
    name: NoName13;
    organization?: Organization;
    organization_id: NoName17;
    position?: Position;
    position_id: NoName21;
}
export interface CompetenceInline {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    parent_id?: ParentId;
}
export interface IndustrySector {
    description?: NoName8;
    id?: ID2;
    is_verified?: NoName9;
    name: NoName10;
}
export interface Organization {
    description?: NoName14;
    id?: ID3;
    is_customer?: NoName15;
    name: NoName16;
}
export interface Position {
    description?: NoName18;
    id?: ID4;
    is_verified?: NoName19;
    name: NoName20;
}
