/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = EducationGraduate;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type NoName3 = number;

export interface EducationGraduate {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
    sorting?: NoName3;
}
