/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = TimeSheetRowRead;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = number;
export type NoName3 = number;
export type NoName4 = number;
export type NoName5 = 'all' | 'weekends' | 'workdays';
export type NoName6 = string;
export type NoName7 = 'F' | 'M';
export type ID = number;
export type NoName8 = string;
export type NoName9 = number;
export type NoName10 = string;
export type NoName11 = number;
export type Photo = string;
export type NoName12 = number;
export type NoName13 = string;
export type NoName14 = string;
export type NoName15 = number;
export type NoName16 = number;
export type NoName17 = string;
export type NoName18 = string;
export type ID1 = number;
export type NoName19 = string;
export type NoName20 = string;
export type ID2 = number;
export type NoName21 = number;
export type NoName22 = string;
export type NoName23 = string;
export type NoName24 = '-' | 'F' | 'M';
export type ID3 = number;
export type NoName25 = string;
export type NoName26 = string;
export type NoName27 = string;
export type Photo1 = string;
export type NoName28 = number;
export type NoName29 = string;
export type NoName30 = string;
export type NoName31 = string;
export type DifficultyFactor = number;
export type NoName32 = string;
export type NoName33 = string;
export type NoName34 = string;
export type NoName35 = number;
export type NoName36 = number;
export type ID4 = number;
export type NoName37 = string;
export type NoName38 = number;
export type NoName39 = string;
export type NoName40 = number;
export type NoName41 = string;
export type NoName42 = string;
export type ID5 = number;
export type NoName43 = string;
export type NoName44 = string;
export type NoName45 = string;
export type ID6 = number;
export type NoName46 = boolean;
export type NoName47 = boolean;
export type NoName48 = string;
export type NoName49 = string;
export type NoName50 = number;
export type NoName51 = string;
export type NoName52 = number;
/**
 * в часах
 */
export type NoName53 = number;
export type ID7 = number;
export type NoName54 = string;
export type ID8 = number;
export type NoName55 = boolean;
export type NoName56 = string;
export type NoName57 = number;
export type NoName58 = number;
export type NoName59 = string;
export type NoName60 = string;
export type NoName61 = number;
export type ID9 = number;
export type NoName62 = number;
export type NoName63 = string;
export type NoName64 = number;
export type NoName65 = string;
export type NoName66 = string;
export type ID10 = number;
export type NoName67 = number;
export type NoName68 = string;
export type NoName69 = string;
export type NoName70 = string;
export type NoName71 = string;
export type NoName72 = string;
export type NoName73 = string;
export type ID11 = number;
export type NoName74 = string;
export type ID12 = number;
export type NoName75 = boolean;
export type NoName76 = string;
export type NoName77 = number;
export type NoName78 = number;
export type NoName79 = number;
export type NoName80 = string;
export type NoName81 = number;
export type NoName82 = number;
export type NoName83 = string;
export type RequestsRequirementsCountTotal = number;
export type NoName84 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName85 = string;
export type NoName86 = number;
export type NoName87 = number;
export type NoName88 = string;
export type NoName89 = number;
export type ID13 = number;
export type NoName90 = number;
export type NoName91 = number;
export type NoName92 = number;
export type NoName93 = string;
export type NoName94 = number;
export type NoName95 = string;
export type NoName96 = string;
/**
 * если пусто, заполнится автоматически из расчета пятидневной рабочей недели<br>ПН-ПТ deadline_date-start_date
 */
export type NoName97 = number;
export type NoName98 = number;
export type NoName99 = number;
export type NoName100 = 10 | 20 | 30;
export type NoName101 = string;
export type NoName102 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName103 = string;
export type NoName104 = number;
export type NoName105 = number;
export type NoName106 = string;
export type NoName107 = string;
export type NoName108 = string;
export type NoName109 = number;

export interface TimeSheetRowRead {
    created_at?: NoName;
    cv: CvInlineShort;
    cv_id: NoName16;
    date_from?: NoName17;
    date_to?: NoName18;
    id?: ID1;
    request: RequestInline;
    request_id: NoName105;
    task_description?: NoName106;
    task_name: NoName107;
    updated_at?: NoName108;
    work_time: NoName109;
}
export interface CvInlineShort {
    birth_date?: NoName1;
    citizenship_id?: NoName2;
    city_id?: NoName3;
    country_id?: NoName4;
    days_to_contact?: null | NoName5;
    first_name?: NoName6;
    gender?: null | NoName7;
    id?: ID;
    last_name?: NoName8;
    manager_rm_id?: NoName9;
    middle_name?: NoName10;
    organization_contractor_id: NoName11;
    photo?: Photo;
    price?: NoName12;
    time_to_contact_from?: NoName13;
    time_to_contact_to?: NoName14;
    user_id?: NoName15;
}
export interface RequestInline {
    deadline_date?: NoName19;
    description?: NoName20;
    id?: ID2;
    industry_sector_id?: NoName21;
    manager_rm?: UserInline;
    manager_rm_id?: NoName28;
    module?: ModuleInline;
    module_id: NoName99;
    priority?: NoName100;
    start_date?: NoName101;
    status?: NoName102;
    title?: NoName103;
    type_id?: NoName104;
}
export interface UserInline {
    birth_date?: NoName22;
    first_name?: NoName23;
    gender?: null | NoName24;
    id?: ID3;
    last_name?: NoName25;
    middle_name?: NoName26;
    phone?: NoName27;
    photo?: Photo1;
}
export interface ModuleInline {
    created_at?: NoName29;
    deadline_date?: NoName30;
    description?: NoName31;
    difficulty_factor?: DifficultyFactor;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName66;
    id?: ID10;
    manager?: UserInline;
    manager_id?: NoName67;
    name: NoName68;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName86;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName94;
    start_date?: NoName95;
    updated_at?: NoName96;
    work_days_count?: NoName97;
    work_days_hours_count?: NoName98;
}
export interface ModuleFunPointInline {
    created_at?: NoName32;
    description?: NoName33;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName40;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName61;
    id?: ID9;
    module_id: NoName62;
    name: NoName63;
    sorting?: NoName64;
    updated_at?: NoName65;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName34;
    factor?: NoName35;
    fun_point_type_id: NoName36;
    id?: ID4;
    name: NoName37;
    sorting?: NoName38;
    updated_at?: NoName39;
}
export interface FunPointTypeInline {
    created_at?: NoName41;
    description?: NoName42;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID5;
    name: NoName43;
    organization_customer?: MainOrganization;
    organization_customer_id?: NoName50;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName60;
}
export interface MainOrganization {
    created_at?: NoName44;
    current_user_roles?: ('admin' | 'pfm' | 'pm' | 'rm')[];
    description?: NoName45;
    id?: ID6;
    is_contractor?: NoName46;
    is_customer?: NoName47;
    name: NoName48;
    updated_at?: NoName49;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName51;
    fun_point_type_id: NoName52;
    hours?: NoName53;
    id?: ID7;
    position?: Position;
    position_id: NoName57;
    sorting?: NoName58;
    updated_at?: NoName59;
}
export interface Position {
    description?: NoName54;
    id?: ID8;
    is_verified?: NoName55;
    name: NoName56;
}
export interface OrganizationProjectInline {
    created_at?: NoName69;
    current_user_roles?: ('admin' | 'pfm' | 'pm' | 'rm')[];
    date_from?: NoName70;
    date_to?: NoName71;
    description?: NoName72;
    goals?: NoName73;
    id?: ID11;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName77;
    manager_pfm?: UserInline;
    manager_pfm_id?: NoName78;
    manager_pm?: UserInline;
    manager_pm_id?: NoName79;
    name: NoName80;
    organization_contractor?: MainOrganization;
    organization_contractor_id: NoName81;
    organization_customer?: MainOrganization;
    organization_customer_id: NoName82;
    plan_description?: NoName83;
    requests_requirements_count_by_status?: RequestsRequirementsCountByStatus;
    requests_requirements_count_total?: RequestsRequirementsCountTotal;
    status?: NoName84;
    updated_at?: NoName85;
}
export interface IndustrySector {
    description?: NoName74;
    id?: ID12;
    is_verified?: NoName75;
    name: NoName76;
}
export interface RequestsRequirementsCountByStatus {}
export interface ModulePositionLaborEstimateInline {
    count?: NoName87;
    created_at?: NoName88;
    hours?: NoName89;
    id?: ID13;
    module_id: NoName90;
    position?: Position;
    position_id: NoName91;
    sorting?: NoName92;
    updated_at?: NoName93;
}
