/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = RequestRead;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = string;
export type ID1 = number;
export type NoName3 = boolean;
export type NoName4 = string;
export type NoName5 = number;
export type NoName6 = string;
export type NoName7 = string;
export type NoName8 = '-' | 'F' | 'M';
export type ID2 = number;
export type NoName9 = string;
export type NoName10 = string;
export type NoName11 = string;
export type Photo = string;
export type NoName12 = number;
export type NoName13 = string;
export type NoName14 = string;
export type NoName15 = string;
export type DifficultyFactor = number;
export type NoName16 = string;
export type NoName17 = string;
export type NoName18 = string;
export type NoName19 = number;
export type NoName20 = number;
export type ID3 = number;
export type NoName21 = string;
export type NoName22 = number;
export type NoName23 = string;
export type NoName24 = number;
export type NoName25 = string;
export type NoName26 = string;
export type ID4 = number;
export type NoName27 = string;
export type NoName28 = string;
export type NoName29 = string;
export type ID5 = number;
export type NoName30 = boolean;
export type NoName31 = boolean;
export type NoName32 = string;
export type NoName33 = string;
export type NoName34 = number;
export type NoName35 = string;
export type NoName36 = number;
/**
 * в часах
 */
export type NoName37 = number;
export type ID6 = number;
export type NoName38 = string;
export type ID7 = number;
export type NoName39 = boolean;
export type NoName40 = string;
export type NoName41 = number;
export type NoName42 = number;
export type NoName43 = string;
export type NoName44 = string;
export type NoName45 = number;
export type ID8 = number;
export type NoName46 = number;
export type NoName47 = string;
export type NoName48 = number;
export type NoName49 = string;
export type NoName50 = string;
export type ID9 = number;
export type NoName51 = number;
export type NoName52 = string;
export type NoName53 = string;
export type NoName54 = string;
export type NoName55 = string;
export type NoName56 = string;
export type NoName57 = string;
export type ID10 = number;
export type NoName58 = number;
export type NoName59 = number;
export type NoName60 = string;
export type NoName61 = number;
export type NoName62 = number;
export type NoName63 = string;
export type NoName64 = string;
export type NoName65 = number;
export type NoName66 = number;
export type NoName67 = string;
export type NoName68 = number;
export type ID11 = number;
export type NoName69 = number;
export type NoName70 = number;
export type NoName71 = number;
export type NoName72 = string;
export type NoName73 = number;
export type NoName74 = string;
export type NoName75 = string;
/**
 * если пусто, заполнится автоматически из расчета пятидневной рабочей недели<br>ПН-ПТ deadline_date-start_date
 */
export type NoName76 = number;
export type NoName77 = number;
export type NoName78 = number;
export type NoName79 = 10 | 20 | 30;
export type NoName80 = number;
export type ID12 = number;
export type NoName81 = string;
export type ParentId = string;
export type NoName82 = number;
/**
 * `1` : *Менее года*
 * `3` : *1 – 3 года*
 * `5` : *3 - 5 лет*
 * `100` : *Более 5 лет*
 */
export type NoName83 = 1 | 100 | 3 | 5;
export type ID13 = number;
export type RequestRequirementId = string;
export type NoName84 = number;
export type NoName85 = number;
export type NoName86 = string;
export type NoName87 = string;
export type NoName88 = number;
export type NoName89 = number;
export type NoName90 = number;
export type NoName91 = 'all' | 'weekends' | 'workdays';
export type NoName92 = string;
export type NoName93 = 'F' | 'M';
export type ID14 = number;
export type NoName94 = boolean;
export type NoName95 = string;
export type NoName96 = string;
export type NoName97 = number;
export type Photo1 = string;
export type NoName98 = number;
export type NoName99 = string;
export type NoName100 = string;
export type NoName101 = number;
export type CvId = string;
export type NoName102 = string;
export type NoName103 = string;
export type ID15 = number;
export type Date = string;
export type NoName104 = number;
export type NoName105 = number;
export type RequestRequirementId1 = string;
export type NoName106 = 'canceled' | 'candidate' | 'pre-candidate' | 'worker';
export type NoName107 = string;
export type NoName108 = string;
export type NoName109 = string;
export type NoName110 = string;
/**
 * float
 */
export type NoName111 = number;
export type ID16 = number;
export type NoName112 = number;
export type NoName113 = string;
export type NoName114 = number;
export type NoName115 = number;
export type NoName116 = number;
export type NoName117 = string;
export type ID17 = number;
export type NoName118 = boolean;
export type NoName119 = string;
export type NoName120 = number;
export type NoName121 = string;
export type NoName122 = string;
export type ID18 = number;
export type NoName123 = boolean;
export type NoName124 = string;
export type NoName125 = string;
export type ID19 = number;
export type NoName126 = boolean;
export type NoName127 = string;
export type NoName128 = number;
export type RequirementsCountSum = number;
export type NoName129 = number;
export type NoName130 = string;
export type NoName131 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName132 = string;
export type ID20 = number;
export type NoName133 = string;
export type NoName134 = number;

export interface RequestRead {
    deadline_date?: NoName;
    description?: NoName1;
    id?: ID;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName5;
    manager?: UserInline;
    manager_id?: NoName12;
    module?: ModuleInline;
    module_id: NoName78;
    priority?: NoName79;
    recruiter?: UserInline;
    recruiter_id?: NoName80;
    requirements?: RequestRequirementRead[];
    requirements_count_sum?: RequirementsCountSum;
    resource_manager?: UserInline;
    resource_manager_id?: NoName129;
    start_date?: NoName130;
    status?: NoName131;
    title?: NoName132;
    type?: RequestType;
    type_id?: NoName134;
}
export interface IndustrySector {
    description?: NoName2;
    id?: ID1;
    is_verified?: NoName3;
    name: NoName4;
}
export interface UserInline {
    birth_date?: NoName6;
    first_name?: NoName7;
    gender?: null | NoName8;
    id?: ID2;
    last_name?: NoName9;
    middle_name?: NoName10;
    phone?: NoName11;
    photo?: Photo;
}
export interface ModuleInline {
    created_at?: NoName13;
    deadline_date?: NoName14;
    description?: NoName15;
    difficulty_factor?: DifficultyFactor;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName50;
    id?: ID9;
    manager?: UserInline;
    manager_id?: NoName51;
    name: NoName52;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName65;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName73;
    start_date?: NoName74;
    updated_at?: NoName75;
    work_days_count?: NoName76;
    work_days_hours_count?: NoName77;
}
export interface ModuleFunPointInline {
    created_at?: NoName16;
    description?: NoName17;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName24;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName45;
    id?: ID8;
    module_id: NoName46;
    name: NoName47;
    sorting?: NoName48;
    updated_at?: NoName49;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName18;
    factor?: NoName19;
    fun_point_type_id: NoName20;
    id?: ID3;
    name: NoName21;
    sorting?: NoName22;
    updated_at?: NoName23;
}
export interface FunPointTypeInline {
    created_at?: NoName25;
    description?: NoName26;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID4;
    name: NoName27;
    organization_customer?: Organization;
    organization_customer_id?: NoName34;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName44;
}
export interface Organization {
    created_at?: NoName28;
    description?: NoName29;
    id?: ID5;
    is_contractor?: NoName30;
    is_customer?: NoName31;
    name: NoName32;
    updated_at?: NoName33;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName35;
    fun_point_type_id: NoName36;
    hours?: NoName37;
    id?: ID6;
    position?: Position;
    position_id: NoName41;
    sorting?: NoName42;
    updated_at?: NoName43;
}
export interface Position {
    description?: NoName38;
    id?: ID7;
    is_verified?: NoName39;
    name: NoName40;
}
export interface OrganizationProjectInline {
    created_at?: NoName53;
    date_from?: NoName54;
    date_to?: NoName55;
    description?: NoName56;
    goals?: NoName57;
    id?: ID10;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName58;
    manager?: UserInline;
    manager_id?: NoName59;
    name: NoName60;
    organization_contractor?: Organization;
    organization_contractor_id: NoName61;
    organization_customer?: Organization;
    organization_customer_id: NoName62;
    plan_description?: NoName63;
    updated_at?: NoName64;
}
export interface ModulePositionLaborEstimateInline {
    count?: NoName66;
    created_at?: NoName67;
    hours?: NoName68;
    id?: ID11;
    module_id: NoName69;
    position?: Position;
    position_id: NoName70;
    sorting?: NoName71;
    updated_at?: NoName72;
}
export interface RequestRequirementRead {
    competencies?: RequestRequirementCompetenceRead[];
    count?: NoName85;
    cv_list?: RequestRequirementCvRead[];
    cv_list_ids?: string[];
    date_from?: NoName108;
    date_to?: NoName109;
    description?: NoName110;
    experience_years?: NoName111;
    id?: ID16;
    max_price?: NoName112;
    name?: NoName113;
    position?: Position;
    position_id?: NoName114;
    request_id: NoName115;
    sorting?: NoName116;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id?: NoName120;
    work_location_address?: NoName121;
    work_location_city?: City;
    work_location_city_id?: NoName128;
}
export interface RequestRequirementCompetenceRead {
    competence?: Competence;
    competence_id: NoName82;
    experience_years?: NoName83;
    id?: ID13;
    request_requirement_id?: RequestRequirementId;
    sorting?: NoName84;
}
export interface Competence {
    id?: ID12;
    name: NoName81;
    parent_id?: ParentId;
}
export interface RequestRequirementCvRead {
    created_at?: NoName86;
    cv?: CvInlineShort;
    cv_id?: CvId;
    date_from?: NoName102;
    date_to?: NoName103;
    id?: ID15;
    organization_project_card_items?: RequestRequirementCvOrganizationProjectCardItem[];
    rating?: NoName105;
    request_requirement_id?: RequestRequirementId1;
    status?: NoName106;
    updated_at?: NoName107;
}
export interface CvInlineShort {
    birth_date?: NoName87;
    citizenship_id?: NoName88;
    city_id?: NoName89;
    country_id?: NoName90;
    days_to_contact?: null | NoName91;
    first_name?: NoName92;
    gender?: null | NoName93;
    id?: ID14;
    is_resource_owner?: NoName94;
    last_name?: NoName95;
    middle_name?: NoName96;
    organization_contractor_id: NoName97;
    photo?: Photo1;
    price?: NoName98;
    time_to_contact_from?: NoName99;
    time_to_contact_to?: NoName100;
    user_id?: NoName101;
}
export interface RequestRequirementCvOrganizationProjectCardItem {
    date?: Date;
    id: NoName104;
}
export interface TypeOfEmployment {
    description?: NoName117;
    id?: ID17;
    is_verified?: NoName118;
    name: NoName119;
}
export interface City {
    country: Country;
    description?: NoName125;
    id?: ID19;
    is_verified?: NoName126;
    name: NoName127;
}
export interface Country {
    description?: NoName122;
    id?: ID18;
    is_verified?: NoName123;
    name: NoName124;
}
export interface RequestType {
    id?: ID20;
    name: NoName133;
}
