/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = RequestRead;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = string;
export type ID1 = number;
export type NoName3 = boolean;
export type NoName4 = string;
export type NoName5 = number;
export type NoName6 = string;
export type ID2 = number;
export type NoName7 = string;
export type Photo = string;
export type NoName8 = number;
export type NoName9 = string;
export type NoName10 = string;
export type NoName11 = string;
export type Difficulty = number;
export type NoName12 = string;
export type NoName13 = string;
export type NoName14 = string;
export type NoName15 = number;
export type NoName16 = number;
export type ID3 = number;
export type NoName17 = string;
export type NoName18 = number;
export type NoName19 = string;
export type NoName20 = number;
export type NoName21 = string;
export type NoName22 = string;
export type ID4 = number;
export type NoName23 = string;
export type NoName24 = string;
export type ID5 = number;
export type NoName25 = boolean;
export type NoName26 = string;
export type NoName27 = number;
export type NoName28 = string;
export type NoName29 = number;
/**
 * в часах
 */
export type NoName30 = number;
export type ID6 = number;
export type NoName31 = string;
export type ID7 = number;
export type NoName32 = boolean;
export type NoName33 = string;
export type NoName34 = number;
export type NoName35 = number;
export type NoName36 = string;
export type NoName37 = string;
export type NoName38 = number;
export type ID8 = number;
export type NoName39 = number;
export type NoName40 = string;
export type NoName41 = number;
export type NoName42 = string;
export type NoName43 = string;
export type ID9 = number;
export type NoName44 = number;
export type NoName45 = string;
export type NoName46 = string;
export type NoName47 = string;
export type NoName48 = string;
export type NoName49 = string;
export type ID10 = number;
export type NoName50 = number;
export type NoName51 = number;
export type ModulesCount = number;
export type NoName52 = string;
export type NoName53 = number;
export type NoName54 = number;
export type NoName55 = number;
export type NoName56 = string;
export type NoName57 = number;
export type NoName58 = number;
export type NoName59 = string;
export type NoName60 = number;
export type ID11 = number;
export type NoName61 = number;
export type NoName62 = number;
export type NoName63 = number;
export type NoName64 = string;
export type NoName65 = number;
export type NoName66 = string;
export type NoName67 = string;
export type NoName68 = number;
export type NoName69 = 10 | 20 | 30;
export type NoName70 = number;
export type ID12 = number;
export type NoName71 = string;
export type ParentId = string;
export type NoName72 = number;
/**
 * `1` : *Менее года*
 * `3` : *1 – 3 года*
 * `5` : *3 - 5 лет*
 * `100` : *Более 5 лет*
 */
export type NoName73 = 1 | 100 | 3 | 5;
export type ID13 = number;
export type RequestRequirementId = string;
export type NoName74 = number;
export type NoName75 = number;
export type NoName76 = string;
export type NoName77 = string;
export type NoName78 = number;
export type NoName79 = number;
export type NoName80 = number;
export type NoName81 = 'all' | 'weekends' | 'workdays';
export type NoName82 = string;
export type NoName83 = 'F' | 'M';
export type ID14 = number;
export type NoName84 = boolean;
export type NoName85 = string;
export type NoName86 = string;
export type Photo1 = string;
export type NoName87 = number;
export type NoName88 = string;
export type NoName89 = string;
export type NoName90 = number;
export type CvId = string;
export type NoName91 = string;
export type NoName92 = string;
export type ID15 = number;
export type Date = string;
export type NoName93 = number;
export type NoName94 = number;
export type RequestRequirementId1 = string;
export type NoName95 = 'canceled' | 'candidate' | 'pre-candidate' | 'worker';
export type NoName96 = string;
export type NoName97 = string;
export type NoName98 = string;
export type NoName99 = string;
/**
 * float
 */
export type NoName100 = number;
export type ID16 = number;
export type NoName101 = number;
export type NoName102 = string;
export type NoName103 = number;
export type NoName104 = number;
export type NoName105 = number;
export type NoName106 = string;
export type ID17 = number;
export type NoName107 = boolean;
export type NoName108 = string;
export type NoName109 = number;
export type NoName110 = string;
export type NoName111 = string;
export type ID18 = number;
export type NoName112 = boolean;
export type NoName113 = string;
export type NoName114 = string;
export type ID19 = number;
export type NoName115 = boolean;
export type NoName116 = string;
export type NoName117 = number;
export type RequirementsCountSum = number;
export type NoName118 = number;
export type NoName119 = string;
export type NoName120 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName121 = string;
export type ID20 = number;
export type NoName122 = string;
export type NoName123 = number;

export interface RequestRead {
    deadline_date?: NoName;
    description?: NoName1;
    id?: ID;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName5;
    manager?: UserInline;
    manager_id?: NoName8;
    module?: ModuleInline;
    module_id: NoName68;
    priority?: NoName69;
    recruiter?: UserInline;
    recruiter_id?: NoName70;
    requirements?: RequestRequirementRead[];
    requirements_count_sum?: RequirementsCountSum;
    resource_manager?: UserInline;
    resource_manager_id?: NoName118;
    start_date?: NoName119;
    status?: NoName120;
    title?: NoName121;
    type?: RequestType;
    type_id?: NoName123;
}
export interface IndustrySector {
    description?: NoName2;
    id?: ID1;
    is_verified?: NoName3;
    name: NoName4;
}
export interface UserInline {
    first_name: NoName6;
    id?: ID2;
    last_name: NoName7;
    photo?: Photo;
}
export interface ModuleInline {
    created_at?: NoName9;
    deadline_date?: NoName10;
    description?: NoName11;
    difficulty?: Difficulty;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName43;
    id?: ID9;
    manager?: UserInline;
    manager_id?: NoName44;
    name: NoName45;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName57;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName65;
    start_date?: NoName66;
    updated_at?: NoName67;
}
export interface ModuleFunPointInline {
    created_at?: NoName12;
    description?: NoName13;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName20;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName38;
    id?: ID8;
    module_id: NoName39;
    name: NoName40;
    sorting?: NoName41;
    updated_at?: NoName42;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName14;
    factor?: NoName15;
    fun_point_type_id: NoName16;
    id?: ID3;
    name: NoName17;
    sorting?: NoName18;
    updated_at?: NoName19;
}
export interface FunPointTypeInline {
    created_at?: NoName21;
    description?: NoName22;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID4;
    name: NoName23;
    organization?: Organization;
    organization_id?: NoName27;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName37;
}
export interface Organization {
    description?: NoName24;
    id?: ID5;
    is_customer?: NoName25;
    name: NoName26;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName28;
    fun_point_type_id: NoName29;
    hours?: NoName30;
    id?: ID6;
    position?: Position;
    position_id: NoName34;
    sorting?: NoName35;
    updated_at?: NoName36;
}
export interface Position {
    description?: NoName31;
    id?: ID7;
    is_verified?: NoName32;
    name: NoName33;
}
export interface OrganizationProjectInline {
    created_at?: NoName46;
    date_from?: NoName47;
    date_to?: NoName48;
    description?: NoName49;
    id?: ID10;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName50;
    manager?: UserInline;
    manager_id?: NoName51;
    modules_count?: ModulesCount;
    name: NoName52;
    organization?: Organization;
    organization_id: NoName53;
    recruiters?: UserInline[];
    recruiters_ids?: NoName54[];
    resource_managers?: UserInline[];
    resource_managers_ids?: NoName55[];
    updated_at?: NoName56;
}
export interface ModulePositionLaborEstimateInline {
    count?: NoName58;
    created_at?: NoName59;
    hours?: NoName60;
    id?: ID11;
    module_id: NoName61;
    position?: Position;
    position_id: NoName62;
    sorting?: NoName63;
    updated_at?: NoName64;
}
export interface RequestRequirementRead {
    competencies?: RequestRequirementCompetenceRead[];
    count?: NoName75;
    cv_list?: RequestRequirementCvRead[];
    cv_list_ids?: string[];
    date_from?: NoName97;
    date_to?: NoName98;
    description?: NoName99;
    experience_years?: NoName100;
    id?: ID16;
    max_price?: NoName101;
    name?: NoName102;
    position?: Position;
    position_id?: NoName103;
    request_id: NoName104;
    sorting?: NoName105;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id?: NoName109;
    work_location_address?: NoName110;
    work_location_city?: City;
    work_location_city_id?: NoName117;
}
export interface RequestRequirementCompetenceRead {
    competence?: Competence;
    competence_id: NoName72;
    experience_years?: NoName73;
    id?: ID13;
    request_requirement_id?: RequestRequirementId;
    sorting?: NoName74;
}
export interface Competence {
    id?: ID12;
    name: NoName71;
    parent_id?: ParentId;
}
export interface RequestRequirementCvRead {
    created_at?: NoName76;
    cv?: CvInlineShort;
    cv_id?: CvId;
    date_from?: NoName91;
    date_to?: NoName92;
    id?: ID15;
    organization_project_card_items?: RequestRequirementCvOrganizationProjectCardItem[];
    rating?: NoName94;
    request_requirement_id?: RequestRequirementId1;
    status?: NoName95;
    updated_at?: NoName96;
}
export interface CvInlineShort {
    birth_date?: NoName77;
    citizenship_id?: NoName78;
    city_id?: NoName79;
    country_id?: NoName80;
    days_to_contact?: null | NoName81;
    first_name?: NoName82;
    gender?: null | NoName83;
    id?: ID14;
    is_resource_owner?: NoName84;
    last_name?: NoName85;
    middle_name?: NoName86;
    photo?: Photo1;
    price?: NoName87;
    time_to_contact_from?: NoName88;
    time_to_contact_to?: NoName89;
    user_id?: NoName90;
}
export interface RequestRequirementCvOrganizationProjectCardItem {
    date?: Date;
    id: NoName93;
}
export interface TypeOfEmployment {
    description?: NoName106;
    id?: ID17;
    is_verified?: NoName107;
    name: NoName108;
}
export interface City {
    country: Country;
    description?: NoName114;
    id?: ID19;
    is_verified?: NoName115;
    name: NoName116;
}
export interface Country {
    description?: NoName111;
    id?: ID18;
    is_verified?: NoName112;
    name: NoName113;
}
export interface RequestType {
    id?: ID20;
    name: NoName122;
}
