/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvFileRead;
export type CvId = string;
export type NoName = string;
export type FileExt = string;
export type NoName1 = null | string;
export type FileSize = string;
export type ID = number;

export interface CvFileRead {
    cv_id?: CvId;
    file?: NoName;
    file_ext?: FileExt;
    file_name?: NoName1;
    file_size?: FileSize;
    id?: ID;
}
