/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvContact;
export type NoName = string;
export type ContactTypeId = number;
export type CvId = number;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;

export interface CvContact {
    comment?: NoName;
    contact_type_id: ContactTypeId;
    cv_id: CvId;
    id?: ID;
    is_primary?: NoName1;
    value: NoName2;
}
