/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = ProjectRead;
export type NoName = string;
export type NoName1 = null | string;
export type ID = number;
export type NoName2 = string;
export type UserInline = null | {
    first_name: NoName3;
    id?: ID1;
    last_name: NoName4;
    photo?: Photo;
    [k: string]: unknown;
};
export type NoName3 = string;
export type ID1 = number;
export type NoName4 = string;
export type Photo = null | string;
export type NoName5 = string;

export interface ProjectRead {
    created_at?: NoName;
    description?: NoName1;
    id?: ID;
    name: NoName2;
    recruiters?: UserInline[];
    recruiters_ids?: (number | null)[];
    resource_managers?: UserInline[];
    resource_managers_ids?: (number | null)[];
    updated_at?: NoName5;
}
