/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = Competence;
export type Aliases = string;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type Lft = number;
export type MpttLevel = number;
export type NoName2 = string;
export type NoName3 = number;
export type Rght = number;
export type TreeId = number;

export interface Competence {
    aliases?: Aliases[];
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    lft?: Lft;
    mptt_level?: MpttLevel;
    name: NoName2;
    parent?: NoName3;
    rght?: Rght;
    tree_id?: TreeId;
}
