/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = ModuleRead;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type DifficultyFactor = number;
export type NoName3 = string;
export type NoName4 = string;
export type NoName5 = string;
export type NoName6 = number;
export type NoName7 = number;
export type ID = number;
export type NoName8 = string;
export type NoName9 = number;
export type NoName10 = string;
export type NoName11 = number;
export type NoName12 = string;
export type NoName13 = string;
export type ID1 = number;
export type NoName14 = string;
export type NoName15 = string;
export type EMail = string;
export type NoName16 = string;
export type NoName17 = string;
export type NoName18 = string;
export type NoName19 = string;
export type ID2 = number;
export type NoName20 = boolean;
export type NoName21 = boolean;
export type NoName22 = boolean;
export type NoName23 = string;
export type NoName24 = string;
export type NoName25 = string;
export type NoName26 = string;
export type NoName27 = number;
export type NoName28 = string;
export type NoName29 = number;
/**
 * в часах
 */
export type NoName30 = number;
export type ID3 = number;
export type NoName32 = string;
export type ID4 = number;
export type NoName33 = boolean;
export type NoName34 = string;
export type NoName35 = number;
export type NoName36 = number;
export type NoName37 = string;
export type NoName38 = string;
export type NoName39 = number;
export type ID5 = number;
export type NoName40 = number;
export type NoName41 = string;
export type NoName42 = number;
export type NoName43 = string;
export type NoName44 = string;
export type ID6 = number;
export type NoName45 = string;
export type NoName46 = string;
export type NoName47 = string;
export type NoName48 = string;
export type NoName49 = string;
export type NoName50 = string;
export type ID7 = number;
export type NoName52 = string;
export type ID8 = number;
export type NoName53 = boolean;
export type NoName54 = string;
export type NoName55 = number;
export type NoName56 = string;
export type NoName57 = string;
export type NoName58 = '-' | 'F' | 'M';
export type ID9 = number;
export type NoName59 = string;
export type NoName60 = string;
export type NoName61 = string;
export type Photo = string;
export type NoName62 = number;
export type NoName63 = number;
export type NoName64 = string;
export type NoName65 = number;
export type NoName66 = number;
export type NoName67 = string;
export type RequestsRequirementsCountTotal = number;
export type NoName68 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName69 = string;
export type NoName70 = number;
export type NoName71 = number;
export type NoName72 = string;
export type NoName73 = number;
export type ID10 = number;
export type NoName74 = number;
export type NoName75 = number;
export type NoName76 = number;
export type NoName77 = string;
export type NoName78 = number;
export type NoName79 = string;
export type NoName80 = string;
/**
 * если пусто, заполнится автоматически из расчета пятидневной рабочей недели<br>ПН-ПТ deadline_date-start_date
 */
export type NoName81 = number;
export type NoName82 = number;

export interface ModuleRead {
    created_at?: NoName;
    deadline_date?: NoName1;
    description?: NoName2;
    difficulty_factor?: DifficultyFactor;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName44;
    id?: ID6;
    name: NoName45;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName70;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName78;
    start_date?: NoName79;
    updated_at?: NoName80;
    work_days_count?: NoName81;
    work_days_hours_count?: NoName82;
}
export interface ModuleFunPointInline {
    created_at?: NoName3;
    description?: NoName4;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName11;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName39;
    id?: ID5;
    module_id: NoName40;
    name: NoName41;
    sorting?: NoName42;
    updated_at?: NoName43;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName5;
    factor?: NoName6;
    fun_point_type_id: NoName7;
    id?: ID;
    name: NoName8;
    sorting?: NoName9;
    updated_at?: NoName10;
}
export interface FunPointTypeInline {
    created_at?: NoName12;
    description?: NoName13;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID1;
    name: NoName14;
    organization_customer?: MainOrganization;
    organization_customer_id?: NoName27;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName38;
}
export interface MainOrganization {
    contact_person?: NoName15;
    contacts_email?: EMail;
    contacts_phone?: NoName16;
    created_at?: NoName17;
    current_user_roles?: ('admin' | 'pfm' | 'pm' | 'rm')[];
    description?: NoName18;
    general_manager_name?: NoName19;
    id?: ID2;
    is_contractor?: NoName20;
    is_customer?: NoName21;
    is_partner?: NoName22;
    legal_name?: NoName23;
    name: NoName24;
    short_name?: NoName25;
    updated_at?: NoName26;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName28;
    fun_point_type_id: NoName29;
    hours?: NoName30;
    id?: ID3;
    position?: Position;
    position_id: NoName35;
    sorting?: NoName36;
    updated_at?: NoName37;
}
export interface Position {
    attributes?: NoName31;
    description?: NoName32;
    id?: ID4;
    is_verified?: NoName33;
    name: NoName34;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName31 {}
export interface OrganizationProjectInline {
    created_at?: NoName46;
    current_user_roles?: ('admin' | 'pfm' | 'pm' | 'rm')[];
    date_from?: NoName47;
    date_to?: NoName48;
    description?: NoName49;
    goals?: NoName50;
    id?: ID7;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName55;
    manager_pfm?: UserInline;
    manager_pfm_id?: NoName62;
    manager_pm?: UserInline;
    manager_pm_id?: NoName63;
    name: NoName64;
    organization_contractor?: MainOrganization;
    organization_contractor_id: NoName65;
    organization_customer?: MainOrganization;
    organization_customer_id: NoName66;
    plan_description?: NoName67;
    requests_requirements_count_by_status?: RequestsRequirementsCountByStatus;
    requests_requirements_count_total?: RequestsRequirementsCountTotal;
    status?: NoName68;
    updated_at?: NoName69;
}
export interface IndustrySector {
    attributes?: NoName51;
    description?: NoName52;
    id?: ID8;
    is_verified?: NoName53;
    name: NoName54;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName51 {}
export interface UserInline {
    birth_date?: NoName56;
    first_name?: NoName57;
    gender?: null | NoName58;
    id?: ID9;
    last_name?: NoName59;
    middle_name?: NoName60;
    phone?: NoName61;
    photo?: Photo;
}
export interface RequestsRequirementsCountByStatus {}
export interface ModulePositionLaborEstimateInline {
    count?: NoName71;
    created_at?: NoName72;
    hours?: NoName73;
    id?: ID10;
    module_id: NoName74;
    position?: Position;
    position_id: NoName75;
    sorting?: NoName76;
    updated_at?: NoName77;
}
