/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = TimeSheetRow;
export type NoName = string;
export type NoName1 = number;
export type NoName2 = string;
export type NoName3 = string;
export type ID = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type NoName8 = number;

export interface TimeSheetRow {
    created_at?: NoName;
    cv_id: NoName1;
    date_from?: NoName2;
    date_to?: NoName3;
    id?: ID;
    request_requirement_id: NoName4;
    task_description?: NoName5;
    task_name: NoName6;
    updated_at?: NoName7;
    work_time: NoName8;
}
