/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvContactRead;
export type NoName = string;
export type NoName2 = string;
export type ID = number;
export type NoName3 = boolean;
export type NoName4 = string;
export type NoName5 = number;
export type NoName6 = number;
export type ID1 = number;
export type NoName7 = boolean;
export type NoName8 = string;

export interface CvContactRead {
    comment?: NoName;
    contact_type?: ContactType;
    contact_type_id: NoName5;
    cv_id: NoName6;
    id?: ID1;
    is_primary?: NoName7;
    value: NoName8;
}
export interface ContactType {
    attributes?: NoName1;
    description?: NoName2;
    id?: ID;
    is_verified?: NoName3;
    name: NoName4;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName1 {}
