/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvContactRead;
export type NoName = string;
export type ID = number;
export type NoName1 = string;
export type NoName2 = number;
export type ContactTypeId = number;
export type CvId = number;
export type ID1 = number;
export type NoName3 = boolean;
export type NoName4 = string;

export interface CvContactRead {
    comment?: NoName;
    contact_type?: ContactType;
    contact_type_id: ContactTypeId;
    cv_id: CvId;
    id?: ID1;
    is_primary?: NoName3;
    value: NoName4;
}
export interface ContactType {
    id?: ID;
    name: NoName1;
    sorting?: NoName2;
}
