/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvContactRead;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = boolean;
export type NoName3 = string;
export type NoName4 = number;
export type ContactTypeId = number;
export type CvId = number;
export type ID1 = number;
export type NoName5 = boolean;
export type NoName6 = string;

export interface CvContactRead {
    comment?: NoName;
    contact_type?: ContactType;
    contact_type_id: ContactTypeId;
    cv_id: CvId;
    id?: ID1;
    is_primary?: NoName5;
    value: NoName6;
}
export interface ContactType {
    description?: NoName1;
    id?: ID;
    is_verified?: NoName2;
    name: NoName3;
    sorting?: NoName4;
}
