/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = CvPosition;
export type CvId = number;
export type ID = number;
export type PositionId = number;
export type NoName = string;

export interface CvPosition {
    competencies_ids?: number[];
    cv_id: CvId;
    id?: ID;
    position_id?: PositionId;
    title?: NoName;
}
