/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = Organization;
export type NoName1 = string;
export type ID = number;
export type NoName2 = boolean;
export type NoName3 = string;

export interface Organization {
    attributes?: NoName;
    description?: NoName1;
    id?: ID;
    is_verified?: NoName2;
    name: NoName3;
}
/**
 * если вы не до конца понимаете назначение этого поля, вам лучше избежать редактирования
 */
export interface NoName {}
