/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvContact;
export type NoName = string;
export type NoName1 = number;
export type NoName2 = number;
export type ID = number;
export type NoName3 = boolean;
export type NoName4 = string;

export interface CvContact {
    comment?: NoName;
    contact_type_id: NoName1;
    cv_id: NoName2;
    id?: ID;
    is_primary?: NoName3;
    value: NoName4;
}
