/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = ModuleFunPointWrite;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = number;
export type NoName3 = number;
export type ID = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = number;
export type NoName7 = string;

export interface ModuleFunPointWrite {
    created_at?: NoName;
    description?: NoName1;
    difficulty_level_id: NoName2;
    fun_point_type_id: NoName3;
    id?: ID;
    module_id: NoName4;
    name: NoName5;
    sorting?: NoName6;
    updated_at?: NoName7;
}
