/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code201 = Project;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = string;
export type NoName3 = string;

export interface Project {
    created_at?: NoName;
    description?: NoName1;
    id?: ID;
    name: NoName2;
    recruiters_ids?: number[];
    resource_managers_ids?: number[];
    updated_at?: NoName3;
}
