/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvListReadFull;
export type NoName = string;
export type NoName1 = string;
export type ID = number;
export type NoName2 = boolean;
export type NoName3 = string;
export type ParentId = string;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = string;
export type NoName7 = string;
export type NoName8 = string;
export type CvCareerId = string;
export type NoName9 = string;
export type FileExt = string;
export type NoName10 = string;
export type FileSize = string;
export type ID1 = number;
export type ID2 = number;
export type NoName11 = boolean;
export type NoName12 = string;
export type ID3 = number;
export type NoName13 = boolean;
export type NoName14 = string;
export type NoName15 = number;
export type NoName16 = string;
export type ID4 = number;
export type NoName17 = boolean;
export type NoName18 = string;
export type NoName19 = number;
export type NoName20 = string;
export type NoName21 = string;
export type NoName22 = string;
export type NoName23 = string;
export type ID5 = number;
export type NoName24 = number;
export type NoName25 = number;
export type NoName26 = string;
export type NoName27 = number;
export type NoName28 = number;
export type NoName29 = number;
export type NoName30 = string;
export type NoName31 = number;
export type NoName32 = number;
export type NoName33 = number;
export type NoName34 = string;
export type NoName35 = string;
export type NoName36 = string;
export type ID6 = number;
export type NoName37 = boolean;
export type NoName38 = string;
export type NoName39 = number;
export type NoName40 = string;
export type ID7 = number;
export type NoName41 = boolean;
export type NoName42 = string;
export type NoName43 = number;
export type NoName44 = string;
export type ID8 = number;
export type NoName45 = boolean;
export type NoName46 = string;
export type NoName47 = number;
export type ID9 = number;
export type NoName48 = boolean;
export type NoName49 = string;
export type NoName50 = string;
export type NoName51 = string;
export type ID10 = number;
export type NoName52 = boolean;
export type NoName53 = string;
export type NoName54 = number;
export type NoName55 = string;
export type ID11 = number;
export type NoName56 = boolean;
export type NoName57 = string;
export type NoName58 = string;
export type ID12 = number;
export type NoName59 = boolean;
export type NoName60 = string;
export type NoName61 = number;
export type NoName62 = string;
export type NoName63 = string;
export type ID13 = number;
export type NoName64 = boolean;
export type NoName65 = string;
export type NoName66 = number;
export type NoName67 = number;
export type ID14 = number;
export type NoName68 = boolean;
export type NoName69 = string;
export type NoName70 = number;
export type NoName71 = 'all' | 'weekends' | 'workdays';
export type NoName72 = number;
export type NoName73 = number;
export type NoName74 = string;
export type NoName75 = string;
export type NoName76 = string;
export type NoName77 = string;
export type NoName78 = number;
export type NoName79 = number;
export type NoName80 = number;
export type ID15 = number;
export type NoName81 = boolean;
export type CvId = string;
export type NoName82 = string;
export type FileExt1 = string;
export type NoName83 = string;
export type FileSize1 = string;
export type ID16 = number;
export type NoName84 = string;
export type NoName85 = 'F' | 'M';
export type ID17 = number;
export type NoName86 = boolean;
export type NoName87 = string;
export type NoName88 = number;
export type NoName89 = string;
export type Photo = string;
export type NoName90 = string;
export type ID18 = number;
export type NoName91 = boolean;
export type NoName92 = string;
export type NoName93 = number;
export type ID19 = number;
export type NoName94 = string;
export type ParentId1 = string;
export type NoName95 = number;
export type CvPositionId = string;
export type Years = number;
export type NoName96 = number;
export type NoName97 = number;
export type CvPositionId1 = string;
export type NoName98 = string;
export type FileExt2 = string;
export type NoName99 = string;
export type FileSize2 = string;
export type ID20 = number;
export type ID21 = number;
export type NoName100 = number;
export type NoName101 = string;
export type YearStarted = number;
export type Years1 = number;
export type NoName102 = number;
export type NoName103 = number;
export type NoName104 = number;
export type NoName105 = string;
export type NoName106 = string;
export type NoName107 = string;
export type ID22 = number;
export type NoName108 = string;
export type ID23 = number;
export type NoName109 = boolean;
export type NoName110 = string;
export type NoName111 = number;
export type NoName112 = boolean;
export type NoName113 = string;
export type NoName114 = number;
export type NoName115 = number;
export type Rating = number;
export type NoName116 = number;
/**
 * `1` : *Менее года*
 * `3` : *1 – 3 года*
 * `5` : *3 - 5 лет*
 * `100` : *Более 5 лет*
 */
export type NoName117 = 1 | 100 | 3 | 5;
export type ID24 = number;
export type RequestRequirementId = string;
export type NoName118 = number;
export type NoName119 = number;
export type NoName120 = string;
export type NoName121 = string;
export type NoName122 = string;
/**
 * float
 */
export type NoName123 = number;
export type ID25 = number;
export type NoName124 = number;
export type NoName125 = string;
export type NoName126 = number;
export type NoName127 = string;
export type NoName128 = string;
export type ID26 = number;
export type NoName129 = number;
export type NoName130 = string;
export type ID27 = number;
export type NoName131 = string;
export type Photo1 = string;
export type NoName132 = number;
export type NoName133 = string;
export type NoName134 = string;
export type NoName135 = string;
export type Difficulty = number;
export type NoName136 = string;
export type NoName137 = string;
export type NoName138 = string;
export type NoName139 = number;
export type NoName140 = number;
export type ID28 = number;
export type NoName141 = string;
export type NoName142 = number;
export type NoName143 = string;
export type NoName144 = number;
export type NoName145 = string;
export type NoName146 = string;
export type ID29 = number;
export type NoName147 = string;
export type NoName148 = number;
export type NoName149 = string;
export type NoName150 = number;
/**
 * в часах
 */
export type NoName151 = number;
export type ID30 = number;
export type NoName152 = number;
export type NoName153 = number;
export type NoName154 = string;
export type NoName155 = string;
export type NoName156 = number;
export type ID31 = number;
export type NoName157 = number;
export type NoName158 = string;
export type NoName159 = number;
export type NoName160 = string;
export type NoName161 = string;
export type ID32 = number;
export type NoName162 = number;
export type NoName163 = string;
export type NoName164 = string;
export type NoName165 = string;
export type NoName166 = string;
export type NoName167 = string;
export type ID33 = number;
export type NoName168 = number;
export type NoName169 = number;
export type ModulesCount = number;
export type NoName170 = string;
export type NoName171 = number;
export type NoName172 = number;
export type NoName173 = number;
export type NoName174 = string;
export type NoName175 = number;
export type NoName176 = number;
export type NoName177 = string;
export type NoName178 = number;
export type ID34 = number;
export type NoName179 = number;
export type NoName180 = number;
export type NoName181 = number;
export type NoName182 = string;
export type NoName183 = number;
export type NoName184 = string;
export type NoName185 = string;
export type NoName186 = number;
export type NoName187 = 10 | 20 | 30;
export type NoName188 = number;
export type NoName189 = number;
export type NoName190 = string;
export type NoName191 = 'closed' | 'done' | 'draft' | 'in_progress';
export type NoName192 = string;
export type ID35 = number;
export type NoName193 = string;
export type NoName194 = number;
export type NoName195 = number;
export type NoName196 = number;
export type NoName197 = string;
export type ID36 = number;
export type NoName198 = boolean;
export type NoName199 = string;
export type NoName200 = number;
export type NoName201 = string;
export type NoName202 = number;
export type NoName203 = number;
export type NoName204 = number;
export type NoName205 = number;
export type NoName206 = string;
export type NoName207 = string;
export type NoName208 = string;
export type ID37 = number;
export type NoName209 = boolean;
export type NoName210 = boolean;
export type NoName211 = 'manual' | 'request_requirement';
export type OrganizationProjectId = number;
export type OrganizationProjectName = string;
export type NoName212 = number;
export type RequestId = number;
export type RequestRequirementId1 = number;
export type RequestRequirementName = string;
export type RequestTitle = string;
export type NoName213 = number;
export type NoName214 = string;
export type NoName215 = string;
export type NoName216 = number;
export type NoName217 = number;

export interface CvListReadFull {
    birth_date?: NoName;
    career?: CvCareerRead[];
    certificates?: CvCertificateRead[];
    citizenship?: Citizenship;
    citizenship_id?: NoName54;
    city?: City;
    city_id?: NoName61;
    contacts?: CvContactRead[];
    country?: Country;
    country_id?: NoName70;
    days_to_contact?: null | NoName71;
    education?: CvEducationRead[];
    files?: CvFileRead[];
    first_name?: NoName84;
    gender?: null | NoName85;
    id?: ID17;
    is_resource_owner?: NoName86;
    last_name?: NoName87;
    linked_ids?: NoName88[];
    middle_name?: NoName89;
    photo?: Photo;
    physical_limitations?: PhysicalLimitation[];
    physical_limitations_ids?: NoName93[];
    positions?: CvPositionRead[];
    price?: NoName102;
    projects?: CvProjectRead[];
    rating: Rating;
    requests_requirements?: CvRequestRequirementInlineSerializer[];
    time_slots?: CvTimeSlotRead[];
    time_to_contact_from?: NoName214;
    time_to_contact_to?: NoName215;
    types_of_employment?: TypeOfEmployment[];
    types_of_employment_ids?: NoName216[];
    user?: UserInline;
    user_id?: NoName217;
}
export interface CvCareerRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName4[];
    cv_id: NoName5;
    date_from?: NoName6;
    date_to?: NoName7;
    description?: NoName8;
    files?: CvCareerFileRead[];
    id?: ID2;
    is_verified?: NoName11;
    organization?: Organization;
    organization_id: NoName15;
    position?: Position;
    position_id?: NoName19;
    projects?: OrganizationProject[];
    projects_ids?: NoName31[];
}
export interface CompetenceInline {
    description?: NoName1;
    id?: ID;
    is_verified?: NoName2;
    name: NoName3;
    parent_id?: ParentId;
}
export interface CvCareerFileRead {
    cv_career_id?: CvCareerId;
    file?: NoName9;
    file_ext?: FileExt;
    file_name?: NoName10;
    file_size?: FileSize;
    id?: ID1;
}
export interface Organization {
    description?: NoName12;
    id?: ID3;
    is_customer?: NoName13;
    name: NoName14;
}
export interface Position {
    description?: NoName16;
    id?: ID4;
    is_verified?: NoName17;
    name: NoName18;
}
export interface OrganizationProject {
    created_at?: NoName20;
    date_from?: NoName21;
    date_to?: NoName22;
    description?: NoName23;
    id?: ID5;
    industry_sector_id?: NoName24;
    manager_id?: NoName25;
    name: NoName26;
    organization_id: NoName27;
    recruiters_ids?: NoName28[];
    resource_managers_ids?: NoName29[];
    updated_at?: NoName30;
}
export interface CvCertificateRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName32[];
    cv_id: NoName33;
    date?: NoName34;
    description?: NoName35;
    education_graduate?: EducationGraduate;
    education_graduate_id: NoName39;
    education_place?: EducationPlace;
    education_place_id: NoName43;
    education_speciality?: EducationSpecialty;
    education_speciality_id: NoName47;
    id?: ID9;
    is_verified?: NoName48;
    name?: NoName49;
    number?: NoName50;
}
export interface EducationGraduate {
    description?: NoName36;
    id?: ID6;
    is_verified?: NoName37;
    name: NoName38;
}
export interface EducationPlace {
    description?: NoName40;
    id?: ID7;
    is_verified?: NoName41;
    name: NoName42;
}
export interface EducationSpecialty {
    description?: NoName44;
    id?: ID8;
    is_verified?: NoName45;
    name: NoName46;
}
export interface Citizenship {
    description?: NoName51;
    id?: ID10;
    is_verified?: NoName52;
    name: NoName53;
}
export interface City {
    country: Country;
    description?: NoName58;
    id?: ID12;
    is_verified?: NoName59;
    name: NoName60;
}
export interface Country {
    description?: NoName55;
    id?: ID11;
    is_verified?: NoName56;
    name: NoName57;
}
export interface CvContactRead {
    comment?: NoName62;
    contact_type?: ContactType;
    contact_type_id: NoName66;
    cv_id: NoName67;
    id?: ID14;
    is_primary?: NoName68;
    value: NoName69;
}
export interface ContactType {
    description?: NoName63;
    id?: ID13;
    is_verified?: NoName64;
    name: NoName65;
}
export interface CvEducationRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName72[];
    cv_id: NoName73;
    date_from?: NoName74;
    date_to?: NoName75;
    description?: NoName76;
    diploma_number?: NoName77;
    education_graduate?: EducationGraduate;
    education_graduate_id: NoName78;
    education_place?: EducationPlace;
    education_place_id: NoName79;
    education_speciality?: EducationSpecialty;
    education_speciality_id: NoName80;
    id?: ID15;
    is_verified?: NoName81;
}
export interface CvFileRead {
    cv_id?: CvId;
    file?: NoName82;
    file_ext?: FileExt1;
    file_name?: NoName83;
    file_size?: FileSize1;
    id?: ID16;
}
export interface PhysicalLimitation {
    description?: NoName90;
    id?: ID18;
    is_verified?: NoName91;
    name: NoName92;
}
export interface CvPositionRead {
    competencies?: CvPositionCompetenceRead[];
    competencies_ids?: NoName96[];
    cv_id: NoName97;
    files?: CvPositionFileRead[];
    id?: ID21;
    position?: Position;
    position_id?: NoName100;
    title?: NoName101;
    year_started?: YearStarted;
    years?: Years1;
}
export interface CvPositionCompetenceRead {
    competence?: Competence;
    competence_id: NoName95;
    cv_position_id?: CvPositionId;
    years?: Years;
}
export interface Competence {
    id?: ID19;
    name: NoName94;
    parent_id?: ParentId1;
}
export interface CvPositionFileRead {
    cv_position_id?: CvPositionId1;
    file?: NoName98;
    file_ext?: FileExt2;
    file_name?: NoName99;
    file_size?: FileSize2;
    id?: ID20;
}
export interface CvProjectRead {
    competencies?: CompetenceInline[];
    competencies_ids?: NoName103[];
    cv_id: NoName104;
    date_from?: NoName105;
    date_to?: NoName106;
    description?: NoName107;
    id?: ID22;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName111;
    is_verified?: NoName112;
    name: NoName113;
    organization?: Organization;
    organization_id: NoName114;
    position?: Position;
    position_id: NoName115;
}
export interface IndustrySector {
    description?: NoName108;
    id?: ID23;
    is_verified?: NoName109;
    name: NoName110;
}
export interface CvRequestRequirementInlineSerializer {
    competencies?: RequestRequirementCompetenceRead[];
    count?: NoName119;
    date_from?: NoName120;
    date_to?: NoName121;
    description?: NoName122;
    experience_years?: NoName123;
    id?: ID25;
    max_price?: NoName124;
    name?: NoName125;
    position?: Position;
    position_id?: NoName126;
    request?: CvRequestInlineSerializer;
    request_id: NoName195;
    sorting?: NoName196;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id?: NoName200;
    work_location_address?: NoName201;
    work_location_city?: City;
    work_location_city_id?: NoName202;
}
export interface RequestRequirementCompetenceRead {
    competence?: Competence;
    competence_id: NoName116;
    experience_years?: NoName117;
    id?: ID24;
    request_requirement_id?: RequestRequirementId;
    sorting?: NoName118;
}
export interface CvRequestInlineSerializer {
    deadline_date?: NoName127;
    description?: NoName128;
    id?: ID26;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName129;
    manager?: UserInline;
    manager_id?: NoName132;
    module?: ModuleInline;
    module_id: NoName186;
    priority?: NoName187;
    recruiter?: UserInline;
    recruiter_id?: NoName188;
    resource_manager?: UserInline;
    resource_manager_id?: NoName189;
    start_date?: NoName190;
    status?: NoName191;
    title?: NoName192;
    type?: RequestType;
    type_id?: NoName194;
}
export interface UserInline {
    first_name: NoName130;
    id?: ID27;
    last_name: NoName131;
    photo?: Photo1;
}
export interface ModuleInline {
    created_at?: NoName133;
    deadline_date?: NoName134;
    description?: NoName135;
    difficulty?: Difficulty;
    fun_points?: ModuleFunPointInline[];
    goals?: NoName161;
    id?: ID32;
    manager?: UserInline;
    manager_id?: NoName162;
    name: NoName163;
    organization_project?: OrganizationProjectInline;
    organization_project_id: NoName175;
    positions_labor_estimates?: ModulePositionLaborEstimateInline[];
    sorting?: NoName183;
    start_date?: NoName184;
    updated_at?: NoName185;
}
export interface ModuleFunPointInline {
    created_at?: NoName136;
    description?: NoName137;
    difficulty_level?: FunPointTypeDifficultyLevelInline;
    difficulty_level_id: NoName144;
    fun_point_type?: FunPointTypeInline;
    fun_point_type_id: NoName156;
    id?: ID31;
    module_id: NoName157;
    name: NoName158;
    sorting?: NoName159;
    updated_at?: NoName160;
}
export interface FunPointTypeDifficultyLevelInline {
    created_at?: NoName138;
    factor?: NoName139;
    fun_point_type_id: NoName140;
    id?: ID28;
    name: NoName141;
    sorting?: NoName142;
    updated_at?: NoName143;
}
export interface FunPointTypeInline {
    created_at?: NoName145;
    description?: NoName146;
    difficulty_levels?: FunPointTypeDifficultyLevelInline[];
    id?: ID29;
    name: NoName147;
    organization?: Organization;
    organization_id?: NoName148;
    positions_labor_estimates?: FunPointTypePositionLaborEstimateInline[];
    updated_at?: NoName155;
}
export interface FunPointTypePositionLaborEstimateInline {
    created_at?: NoName149;
    fun_point_type_id: NoName150;
    hours?: NoName151;
    id?: ID30;
    position?: Position;
    position_id: NoName152;
    sorting?: NoName153;
    updated_at?: NoName154;
}
export interface OrganizationProjectInline {
    created_at?: NoName164;
    date_from?: NoName165;
    date_to?: NoName166;
    description?: NoName167;
    id?: ID33;
    industry_sector?: IndustrySector;
    industry_sector_id?: NoName168;
    manager?: UserInline;
    manager_id?: NoName169;
    modules_count?: ModulesCount;
    name: NoName170;
    organization?: Organization;
    organization_id: NoName171;
    recruiters?: UserInline[];
    recruiters_ids?: NoName172[];
    resource_managers?: UserInline[];
    resource_managers_ids?: NoName173[];
    updated_at?: NoName174;
}
export interface ModulePositionLaborEstimateInline {
    count?: NoName176;
    created_at?: NoName177;
    hours?: NoName178;
    id?: ID34;
    module_id: NoName179;
    position?: Position;
    position_id: NoName180;
    sorting?: NoName181;
    updated_at?: NoName182;
}
export interface RequestType {
    id?: ID35;
    name: NoName193;
}
export interface TypeOfEmployment {
    description?: NoName197;
    id?: ID36;
    is_verified?: NoName198;
    name: NoName199;
}
export interface CvTimeSlotRead {
    city?: City;
    city_id?: NoName203;
    country?: Country;
    country_id?: NoName204;
    cv_id: NoName205;
    date_from?: NoName206;
    date_to?: NoName207;
    description?: NoName208;
    id?: ID37;
    is_free?: NoName209;
    is_work_permit_required?: NoName210;
    kind?: NoName211;
    organization_project_id?: OrganizationProjectId;
    organization_project_name?: OrganizationProjectName;
    price?: NoName212;
    request_id?: RequestId;
    request_requirement_id?: RequestRequirementId1;
    request_requirement_name?: RequestRequirementName;
    request_title?: RequestTitle;
    type_of_employment?: TypeOfEmployment;
    type_of_employment_id: NoName213;
}
