/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = CvPositionRead;
export type NoName = string;
export type ID = number;
export type NoName1 = boolean;
export type NoName2 = string;
export type CvId = number;
export type CvPositionId = string;
export type NoName3 = string;
export type FileExt = string;
export type NoName4 = string;
export type FileSize = string;
export type ID1 = number;
export type ID2 = number;
export type NoName5 = string;
export type ID3 = number;
export type NoName6 = boolean;
export type NoName7 = string;
export type NoName8 = number;
export type PositionId = number;
export type NoName9 = string;

export interface CvPositionRead {
    competencies?: CompetenceInline[];
    competencies_ids?: number[];
    cv_id: CvId;
    files?: CvPositionFileRead[];
    id?: ID2;
    position?: Position;
    position_id: PositionId;
    title?: NoName9;
}
export interface CompetenceInline {
    description?: NoName;
    id?: ID;
    is_verified?: NoName1;
    name: NoName2;
}
export interface CvPositionFileRead {
    cv_position_id?: CvPositionId;
    file?: NoName3;
    file_ext?: FileExt;
    file_name?: NoName4;
    file_size?: FileSize;
    id?: ID1;
}
export interface Position {
    description?: NoName5;
    id?: ID3;
    is_verified?: NoName6;
    name: NoName7;
    sorting?: NoName8;
}
