/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = ModuleWrite;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = string;
export type ID = number;
export type NoName4 = string;
export type NoName5 = number;
export type NoName6 = number;
export type NoName7 = string;
export type NoName8 = string;
/**
 * если пусто, заполнится автоматически из расчета пятидневной рабочей недели<br>ПН-ПТ deadline_date-start_date
 */
export type NoName9 = number;
export type NoName10 = number;

export interface ModuleWrite {
    created_at?: NoName;
    deadline_date?: NoName1;
    description?: NoName2;
    goals?: NoName3;
    id?: ID;
    name: NoName4;
    organization_project_id: NoName5;
    sorting?: NoName6;
    start_date?: NoName7;
    updated_at?: NoName8;
    work_days_count?: NoName9;
    work_days_hours_count?: NoName10;
}
