/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code200 = ModuleWrite;
export type NoName = string;
export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = string;
export type ID = number;
export type NoName4 = number;
export type NoName5 = string;
export type NoName6 = number;
export type NoName7 = number;
export type NoName8 = string;
export type NoName9 = string;

export interface ModuleWrite {
    created_at?: NoName;
    deadline_date?: NoName1;
    description?: NoName2;
    goals?: NoName3;
    id?: ID;
    manager_id?: NoName4;
    name: NoName5;
    organization_project_id: NoName6;
    sorting?: NoName7;
    start_date?: NoName8;
    updated_at?: NoName9;
}
